<?php

namespace Database\Seeders\fac;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class HabilidadTecnicaSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            'Administración, finanzas y gestión empresarial' => [
                'Administración de microempresas familiares',
                'Administración general',
                'Análisis de costos y presupuestos',
                'Auditoría y control interno',
                'Capacitación interna',
                'Conciliaciones bancarias',
                'Contabilidad para emprendedores',
                'Contabilidad y tributación',
                'Contratación laboral básica',
                'Control de caja y bancos',
                'Costeo de productos artesanales',
                'Crédito y financiamiento para pymes',
                'Declaraciones tributarias básicas',
                'Educación financiera comunitaria',
                'Facturación electrónica',
                'Finanzas para pymes',
                'Gestión de asociaciones productivas',
                'Gestión de calidad y procesos',
                'Gestión de compras y abastecimiento',
                'Gestión de cooperativas y asociaciones',
                'Gestión de expedientes de personal',
                'Gestión de nómina en pymes',
                'Gestión de proyectos',
                'Gestión de talento humano',
                'Gestión documental y archivo',
                'Inventarios para pequeños negocios',
                'Nómina y legislación laboral básica',
                'Presupuestos familiares y de negocio',
                'Reclutamiento operativo',
                'Servicio administrativo y secretariado ejecutivo',
            ],
            'Agropecuario, pesca y agroindustria' => [
                'Acuicultura, pesca y procesamiento pesquero',
                'Agricultura orgánica certificada',
                'Agricultura sostenible y producción de cultivos',
                'Agroecología y agricultura familiar',
                'Agroindustria y transformación de alimentos',
                'Apicultura y meliponicultura',
                'Avicultura de traspatio',
                'Café, cacao, azúcar y cultivos tropicales',
                'Comercialización agropecuaria y cadenas cortas',
                'Cooperativismo rural y extensión agrícola',
                'Cultivo de berries y frutos rojos',
                'Cultivo de cereales, legumbres y oleaginosas',
                'Cultivo de frutas, hortalizas y plantas ornamentales',
                'Cultivo de papa y tubérculos andinos',
                'Cultivo de quinoa, amaranto y chía',
                'Ganadería bovina, porcina, avícola y especies menores',
                'Ganadería regenerativa',
                'Manejo integrado de plagas agrícolas',
                'Producción caprina y ovina',
                'Producción de aguacate y mango',
                'Producción de banano y plátano',
                'Producción de cítricos tropicales',
                'Producción de cuyes y conejos',
                'Producción de granos andinos',
                'Producción de maíz y frijol mesoamericano',
                'Producción de palma aceitera sostenible',
                'Riego, maquinaria agrícola y agricultura de precisión',
                'Sanidad animal y fitosanidad',
                'Silvicultura, viveros y manejo forestal',
                'Sistemas silvopastoriles',
            ],
            'Alimentos, bebidas y gastronomía' => [
                'Arepas, empanadas y masas regionales',
                'Barismo y métodos de extracción de café',
                'Café, cacao y chocolatería',
                'Carnes, embutidos y productos cárnicos',
                'Catering y servicio de eventos',
                'Chocolatería bean-to-bar',
                'Cocina de mariscos y cevichería',
                'Cocina internacional',
                'Cocina peruana y nikkei latinoamericana',
                'Cocina regional latinoamericana',
                'Control de calidad alimentaria',
                'Elaboración de pupusas y antojitos centroamericanos',
                'Elaboración de yogur y bebidas lácteas',
                'Emprendimientos gastronómicos',
                'Fermentados latinoamericanos',
                'Gastronomía amazónica',
                'Gastronomía andina',
                'Gastronomía caribeña',
                'Gastronomía mexicana tradicional',
                'Heladería y paletería artesanal',
                'Inocuidad, BPM y manipulación de alimentos',
                'Lácteos y derivados',
                'Nutrición aplicada y dietética básica',
                'Panadería y repostería',
                'Parrilla, asado y cortes latinoamericanos',
                'Procesamiento y conservación de alimentos',
                'Producción artesanal de quesos',
                'Producción de tortillas y derivados de maíz',
                'Servicio de bar, coctelería y bebidas',
                'Tamales, humitas y envueltos',
            ],
            'Artes, cultura, comunicación y economía creativa' => [
                'Animación y contenido digital',
                'Artes plásticas para emprendimientos',
                'Artes visuales y pintura',
                'Artesanías culturales',
                'Comunicación para organizaciones sociales',
                'Comunicación social y periodismo',
                'Danza',
                'Danza folclórica latinoamericana',
                'Diseño de identidad para marcas locales',
                'Diseño editorial básico',
                'Diseño gráfico',
                'Edición de video para redes',
                'Fotografía para emprendimientos',
                'Fotografía y video',
                'Gestión cultural',
                'Gestión de festivales',
                'Gestión de redes para artistas',
                'Ilustración digital',
                'Locución y radio comunitaria',
                'Muralismo comunitario',
                'Música y producción sonora',
                'Periodismo local',
                'Pintura decorativa popular',
                'Producción audiovisual',
                'Producción de eventos culturales',
                'Producción de podcast',
                'Publicidad y branding',
                'Teatro y artes escénicas',
                'Video con celular',
            ],
            'Artesanías, oficios y economía popular' => [
                'Alfarería tradicional',
                'Artesanía en cuero',
                'Bisutería',
                'Bisutería con mostacilla',
                'Bordado tradicional',
                'Cerámica artesanal',
                'Cerámica decorativa',
                'Cerámica utilitaria',
                'Cestería con fibras naturales',
                'Comercialización de artesanías',
                'Decoración y arreglos para eventos',
                'Empaque y presentación de productos artesanales',
                'Escultura en barro',
                'Hamacas y tejidos regionales',
                'Joyería artesanal en plata',
                'Joyería artesanal en semillas',
                'Manualidades navideñas y decorativas',
                'Máscaras y utilería festiva',
                'Pirograbado',
                'Reciclaje creativo',
                'Serigrafía artesanal',
                'Sombreros y fibras vegetales',
                'Tallado en madera',
                'Tejido en palma y tule',
                'Tejidos y bordados artesanales',
                'Telar de cintura',
                'Trabajo en madera y bambú',
                'Velas, parafina y jabonería artesanal',
            ],
            'Automotriz, movilidad y transporte técnico' => [
                'Aire acondicionado automotriz',
                'Alineación y balanceo',
                'Baterías y sistemas de carga',
                'Conducción profesional y seguridad vial aplicada',
                'Diagnóstico computarizado vehicular',
                'Diagnóstico OBD-II',
                'Electricidad y electrónica automotriz',
                'Enderezado, pintura y carrocería',
                'Gestión de talleres automotrices',
                'Instalación de alarmas y accesorios',
                'Inyección diésel common rail',
                'Inyección electrónica gasolina',
                'Logística de flotas',
                'Mantenimiento de bicicletas',
                'Mantenimiento de motocicletas',
                'Mantenimiento de mototaxis',
                'Mantenimiento preventivo automotriz',
                'Maquinaria pesada y equipo agrícola',
                'Mecánica automotriz',
                'Mecánica de buses y transporte público',
                'Mecánica diésel',
                'Mecánica rápida',
                'Reparación de alternadores y arranques',
                'Reparación de motocicletas de trabajo',
                'Reparación de transmisiones',
                'Sistemas de frenos ABS',
                'Sistemas de refrigeración vehicular',
                'Sistemas de suspensión y dirección',
                'Vehículos eléctricos e híbridos',
            ],
            'Belleza, estética y servicios personales' => [
                'Barbería',
                'Barbería clásica',
                'Barbería moderna',
                'Bioseguridad en servicios personales',
                'Colorimetría y tratamientos capilares',
                'Corte de cabello femenino',
                'Corte de cabello masculino',
                'Cosmetología y cuidado facial',
                'Cuidado de piel tropical',
                'Depilación',
                'Diseño de cejas',
                'Estética corporal',
                'Extensiones de pestañas',
                'Gestión de salón de belleza',
                'Imagen personal y asesoría de estilo',
                'Manicure semipermanente',
                'Manicure y pedicure',
                'Maquillaje artístico',
                'Maquillaje para novias',
                'Maquillaje profesional',
                'Maquillaje social',
                'Masajes y terapias de bienestar',
                'Pedicure clínico básico',
                'Peinados para eventos',
                'Peluquería',
                'Tratamientos capilares naturales',
                'Trenzado y peinados afrocaribeños',
                'Uñas acrílicas y gel',
            ],
            'Comercio, ventas y servicios al cliente' => [
                'Atención y experiencia del cliente',
                'Caja y facturación comercial',
                'Catálogos digitales',
                'Cobranza y recuperación de cartera',
                'Comercio exterior básico',
                'CRM y fidelización',
                'Fotografía de producto con celular',
                'Gestión de canales y distribuidores',
                'Gestión de puntos de venta',
                'Gestión de tiendas y retail',
                'Investigación de mercados',
                'Manejo de quejas y reclamos',
                'Marketing para negocios locales',
                'Marketing y comunicación comercial',
                'Merchandising para supermercados',
                'Merchandising y exhibición comercial',
                'Negociación comercial',
                'Promotoría de marca',
                'Protocolos de atención ciudadana',
                'Publicidad en Facebook e Instagram',
                'Servicio al cliente presencial',
                'Ventas B2B para pymes',
                'Ventas consultivas',
                'Ventas digitales y social commerce',
                'Ventas en ferias y bazares',
                'Ventas en mercados populares',
                'Ventas para tiendas de barrio',
                'Ventas por WhatsApp Business',
                'Ventas telefónicas',
            ],
            'Construcción, infraestructura y vivienda' => [
                'Albañilería y acabados',
                'Autoconstrucción asistida',
                'Carpintería de obra blanca',
                'Carpintería para construcción',
                'Construcción con adobe mejorado',
                'Construcción con bahareque y materiales locales',
                'Construcción de vivienda social',
                'Construcción sostenible y eficiencia energética',
                'Electricidad residencial y comercial',
                'Encofrado y armado de hierro',
                'Fontanería, plomería y saneamiento',
                'Gestión de proyectos de construcción',
                'Impermeabilización de techos',
                'Instalación de cielos falsos',
                'Instalación de gas y redes hidráulicas',
                'Instalación de pisos y azulejos',
                'Instalación de techos livianos',
                'Lectura de planos arquitectónicos',
                'Lectura de planos estructurales',
                'Mampostería confinada',
                'Mantenimiento de edificios',
                'Mezclas y concreto en obra',
                'Obras civiles y mantenimiento de infraestructura',
                'Pintura, yesería y revestimientos',
                'Presupuestos de obra menor',
                'Seguridad ocupacional en obra',
                'Soldadura estructural',
                'Supervisión de cuadrillas',
                'Topografía, lectura de planos y cubicación',
            ],
            'Deporte, recreación y vida activa' => [
                'Actividades al aire libre y turismo aventura',
                'Arbitraje y organización deportiva',
                'Ciclismo recreativo',
                'Danza fitness y bienestar físico',
                'Deporte inclusivo',
                'Educación física y recreación',
                'Entrenamiento deportivo',
                'Entrenamiento funcional',
                'Entrenamiento para baloncesto',
                'Entrenamiento para béisbol y softbol',
                'Entrenamiento para fútbol base',
                'Entrenamiento para voleibol',
                'Gestión de escuelas deportivas',
                'Gestión de gimnasios y clubes',
                'Guía de actividades al aire libre',
                'Natación básica',
                'Nutrición deportiva básica',
                'Organización de torneos comunitarios',
                'Preparación física para jóvenes',
                'Prevención de lesiones deportivas',
                'Primeros auxilios deportivos',
                'Recreación comunitaria',
                'Recreación para adultos mayores',
                'Recreación para niñez',
                'Senderismo y trekking',
                'Surf y deportes acuáticos',
            ],
            'Educación, formación y desarrollo humano' => [
                'Alfabetización digital de adultos',
                'Alfabetización y educación básica',
                'Andragogía y educación de adultos',
                'Capacitación en empresas',
                'Diseño curricular por competencias',
                'Diseño de cursos cortos laborales',
                'Educación intercultural bilingüe',
                'Educación popular latinoamericana',
                'Elaboración de guías didácticas',
                'Enseñanza de español para extranjeros',
                'Enseñanza de inglés laboral',
                'Enseñanza de portugués básico',
                'Evaluación de aprendizajes',
                'Evaluación por evidencias',
                'Facilitación de talleres comunitarios',
                'Formación de instructores',
                'Gamificación educativa',
                'Gestión educativa',
                'Idiomas',
                'Inclusión de personas con discapacidad',
                'Inclusión educativa',
                'Metodologías de acompañamiento',
                'Microaprendizaje para adultos',
                'Neurohabilidades y aprendizaje',
                'Orientación vocacional',
                'Producción de clases virtuales',
                'Tutoría para formación técnica',
                'Tutoría virtual y educación en línea',
                'Uso de plataformas LMS',
            ],
            'Emprendimiento, innovación y desarrollo productivo' => [
                'Acceso a microcrédito',
                'Asociaciones de productores',
                'Asociatividad y cadenas productivas',
                'Cooperativas de producción',
                'Costeo para microemprendimientos',
                'Diseño de propuesta de valor',
                'Emprendimiento femenino',
                'Emprendimiento juvenil',
                'Emprendimiento migrante y retornado',
                'Emprendimiento rural',
                'Emprendimientos de economía social',
                'Finanzas para emprendedores',
                'Flujo de caja para microempresas',
                'Formalización empresarial',
                'Formalización tributaria básica',
                'Gestión de microempresas',
                'Habilidades blandas y empleabilidad',
                'Incubación y aceleración',
                'Innovación y mejora de productos',
                'Investigación de clientes para emprendedores',
                'Liderazgo y habilidades directivas',
                'Marketing para emprendedores',
                'Modelo de negocio y plan de empresa',
                'Pitch y presentación de negocios',
                'Propiedad intelectual básica',
                'Prototipado de productos',
                'Transformación digital para pymes',
                'Validación de ideas de negocio',
            ],
            'Energía, agua y saneamiento' => [
                'Auditorías energéticas básicas',
                'Biodigestores rurales',
                'Biogás para pequeñas fincas',
                'Bombeo solar para riego',
                'Captación de agua lluvia',
                'Cloración y monitoreo de agua',
                'Dimensionamiento de sistemas fotovoltaicos',
                'Eficiencia energética',
                'Energía eólica y otras renovables',
                'Energía solar fotovoltaica',
                'Energía solar térmica',
                'Estufas eficientes y cocción limpia',
                'Fontanería para sistemas comunitarios',
                'Gestión de proyectos de energía',
                'Gestión de residuos sólidos',
                'Iluminación eficiente LED',
                'Instalación solar aislada rural',
                'Instalación solar interconectada',
                'Mantenimiento de equipos energéticos',
                'Mantenimiento de paneles solares',
                'Mantenimiento de redes de agua comunitaria',
                'Microhidroenergía comunitaria',
                'Operación de plantas y servicios públicos',
                'Operación de pozos y bombeo',
                'Potabilización rural de agua',
                'Redes eléctricas y distribución',
                'Sistemas de bombeo y riego tecnificado',
                'Tratamiento de agua potable',
                'Tratamiento de aguas residuales',
            ],
            'Gobierno, legal y servicios públicos' => [
                'Administración pública',
                'Archivo público y gestión documental',
                'Atención ciudadana',
                'Atención en ventanilla pública',
                'Catastro y ordenamiento territorial básico',
                'Compras públicas',
                'Compras públicas simplificadas',
                'Contratación pública básica',
                'Cooperación internacional',
                'Cooperación internacional local',
                'Derecho laboral básico',
                'Facilitación de mesas de diálogo',
                'Formulación de proyectos municipales',
                'Gestión de asociaciones comunales',
                'Gestión de expedientes ciudadanos',
                'Gestión de proyectos sociales',
                'Gestión de servicios comunitarios',
                'Gestión municipal',
                'Leyes y normativa general',
                'Organización comunitaria',
                'Participación ciudadana',
                'Políticas públicas y evaluación',
                'Presupuesto participativo',
                'Registro civil y documentación',
                'Servicios registrales y documentación',
                'Trámites municipales básicos',
                'Transparencia municipal',
                'Transparencia y acceso a información',
            ],
            'Industria manufacturera y procesos productivos' => [
                'Cerámica, vidrio y materiales de construcción',
                'Control de calidad industrial',
                'Corte CNC y router industrial',
                'Diseño de moldes y matrices',
                'Extrusión de plásticos',
                'Fabricación de bloques y prefabricados',
                'Fabricación de productos de limpieza',
                'Fabricación de puertas y ventanas',
                'Inyección de plásticos',
                'Joyería, bisutería y manufacturas varias',
                'Lean manufacturing y mejora continua',
                'Madera, muebles y carpintería industrial',
                'Mantenimiento industrial',
                'Metalmecánica y soldadura',
                'Operación de maquinaria industrial',
                'Papel, impresión y empaque',
                'Plásticos, caucho y materiales compuestos',
                'Procesamiento de caucho y llantas',
                'Producción de cosmética natural',
                'Producción de ladrillos y tejas',
                'Producción de muebles seriados',
                'Producción de pinturas y recubrimientos',
                'Producción farmacéutica y cosmética',
                'Química industrial y productos de limpieza',
                'Reciclaje industrial de plásticos',
                'Seguridad industrial en planta',
                'Soldadura MIG y TIG',
                'Soldadura para estructuras livianas',
                'Termoformado y empaque industrial',
                'Tornería y fresado básico',
            ],
            'Logística, transporte y cadena de suministro' => [
                'Almacenamiento de granos',
                'Cadena de frío',
                'Cadena de frío para lácteos',
                'Cadena de frío para medicamentos',
                'Comercio internacional y documentación',
                'Compras estratégicas',
                'Distribución urbana en motocicleta',
                'Documentación aduanera centroamericana',
                'Empaque para envíos nacionales',
                'Exportación de productos agrícolas',
                'Gestión de almacenes e inventarios',
                'Gestión de bodegas pequeñas',
                'Gestión de flotas',
                'Gestión de transporte internacional terrestre',
                'Importación para pymes',
                'Inventario con códigos de barras',
                'Logística agrícola postcosecha',
                'Logística para alimentos perecederos',
                'Logística para comercio electrónico',
                'Logística portuaria y aduanas',
                'Operación de montacargas',
                'Operación de puertos secos',
                'Planificación de demanda',
                'Preparación de pedidos picking y packing',
                'Rutas de reparto local',
                'Seguridad en transporte de carga',
                'Transporte terrestre y distribución',
                'Trazabilidad y sistemas logísticos',
                'Última milla y entregas urbanas',
            ],
            'Medio ambiente, sostenibilidad y economía circular' => [
                'Adaptación climática comunitaria',
                'Agricultura climáticamente inteligente',
                'Bioeconomía y negocios verdes',
                'Cambio climático y adaptación',
                'Centros de acopio comunitarios',
                'Compostaje y gestión orgánica',
                'Conservación de suelos',
                'Economía circular',
                'Ecoturismo y conservación',
                'Educación ambiental',
                'Educación ambiental escolar',
                'Evaluación de impacto ambiental',
                'Gestión ambiental',
                'Gestión de áreas protegidas',
                'Gestión de riesgo climático',
                'Manejo de microcuencas',
                'Medición de huella de carbono básica',
                'Monitoreo ambiental comunitario',
                'Monitoreo de biodiversidad',
                'Prevención de incendios forestales',
                'Producción más limpia',
                'Reciclaje inclusivo con recicladores',
                'Reciclaje y valorización de residuos',
                'Reforestación de cuencas',
                'Restauración de manglares',
                'Restauración ecológica',
                'Reutilización de textiles',
                'Viveros forestales comunitarios',
            ],
            'Minería, hidrocarburos y recursos naturales' => [
                'Beneficio de oro sin mercurio',
                'Consulta y participación comunitaria',
                'Energía y combustibles alternativos',
                'Formalización de pequeña minería',
                'Geología básica aplicada',
                'Gestión ambiental en minería y energía',
                'Lectura de mapas geológicos',
                'Legislación y permisos del sector',
                'Manejo de explosivos básico',
                'Manejo de GLP',
                'Mantenimiento de equipos extractivos',
                'Mantenimiento de estaciones de servicio',
                'Minería aluvial responsable',
                'Minería artesanal y pequeña minería responsable',
                'Muestreo geológico básico',
                'Operación de equipos mineros',
                'Operación segura de gasolineras',
                'Petróleo, gas y combustibles',
                'Procesamiento de minerales',
                'Relacionamiento comunitario',
                'Relaciones comunitarias extractivas',
                'Restauración de áreas mineras',
                'Seguridad en almacenamiento de combustibles',
                'Seguridad en túneles y socavones',
                'Seguridad minera',
                'Transporte de combustibles',
                'Ventilación minera básica',
            ],
            'Salud, cuidado y bienestar comunitario' => [
                'Acompañamiento a personas con discapacidad',
                'Asistencia en vacunación',
                'Atención en clínicas comunitarias',
                'Atención integral a primera infancia',
                'Auxiliar de enfermería y cuidados básicos',
                'Control básico de medicamentos',
                'Cuidado de personas mayores',
                'Cuidado infantil y estimulación temprana',
                'Cuidados domiciliarios de personas mayores',
                'Cuidados paliativos básicos',
                'Estimulación temprana comunitaria',
                'Farmacia y dispensación básica',
                'Gestión de citas y expedientes de salud',
                'Higiene y bioseguridad clínica',
                'Laboratorio clínico básico',
                'Nutrición y hábitos saludables',
                'Prevención de adicciones',
                'Prevención de enfermedades crónicas',
                'Primeros auxilios',
                'Primeros auxilios psicológicos',
                'Promoción de lactancia materna',
                'Rehabilitación y terapia ocupacional básica',
                'Salud comunitaria y promoción de la salud',
                'Salud mental comunitaria',
                'Salud mental y bienestar emocional',
                'Salud sexual y reproductiva comunitaria',
                'Seguridad alimentaria y salud pública',
                'Teleasistencia y atención remota',
                'Toma de signos vitales',
            ],
            'Seguridad, prevención y gestión de riesgos' => [
                'Brigadas de emergencia',
                'Cumplimiento normativo básico',
                'Ergonomía en oficinas y talleres',
                'Espacios confinados',
                'Evacuación y simulacros',
                'Gestión de desastres y protección civil',
                'Identificación de peligros laborales',
                'Investigación de incidentes',
                'Investigación y prevención de pérdidas',
                'Manejo seguro de químicos',
                'Planes de emergencia comunitarios',
                'Planes de emergencia familiares',
                'Prevención de incendios',
                'Prevención de riesgos laborales',
                'Prevención de violencia y acoso laboral',
                'Primeros auxilios en brigadas',
                'Seguridad digital para usuarios',
                'Seguridad en cocinas industriales',
                'Seguridad en construcción',
                'Seguridad en talleres mecánicos',
                'Seguridad privada',
                'Seguridad vial y movilidad segura',
                'Seguridad y salud ocupacional',
                'Seguros y gestión de riesgos',
                'Trabajo seguro en alturas',
                'Uso de equipo de protección personal',
                'Uso de extintores',
            ],
            'Servicios técnicos, mantenimiento y reparación' => [
                'Gestión de servicios generales',
                'Instalación de aire acondicionado mini split',
                'Jardinería y paisajismo',
                'Limpieza hotelera',
                'Limpieza profesional de oficinas',
                'Limpieza, lavandería y mantenimiento doméstico',
                'Mantenimiento de cuartos fríos',
                'Mantenimiento de herramientas eléctricas',
                'Mantenimiento de instalaciones',
                'Refrigeración y aire acondicionado',
                'Reparación de bicicletas',
                'Reparación de bombas de agua',
                'Reparación de calzado y cuero',
                'Reparación de celulares y dispositivos móviles',
                'Reparación de cocinas y estufas',
                'Reparación de computadoras',
                'Reparación de electrodomésticos',
                'Reparación de equipos de audio',
                'Reparación de lavadoras',
                'Reparación de maquinaria pequeña',
                'Reparación de máquinas de coser',
                'Reparación de muebles',
                'Reparación de muebles de madera',
                'Reparación de refrigeradoras',
                'Reparación de televisores',
                'Reparación de ventiladores',
                'Servicios funerarios',
                'Tapicería de muebles',
            ],
            'Tecnología, datos y telecomunicaciones' => [
                'Administración de redes Wi-Fi',
                'Administración de sistemas',
                'Alfabetización digital y ofimática',
                'Analítica de datos para pymes',
                'Automatización con herramientas no-code',
                'Automatización y robótica básica',
                'Bases de datos y analítica de datos',
                'Cableado estructurado',
                'Ciberseguridad',
                'Ciberseguridad para pymes',
                'Comercio electrónico y marketing digital',
                'Computación en la nube',
                'Desarrollo de aplicaciones móviles',
                'Desarrollo de software',
                'Desarrollo web',
                'Excel aplicado a operaciones',
                'Fibra óptica básica',
                'Gestión de mesa de ayuda',
                'Instalación de cámaras de seguridad IP',
                'Inteligencia artificial aplicada',
                'Internet de las cosas',
                'Mantenimiento de cibercafés y centros digitales',
                'Power BI básico',
                'Programación con JavaScript básico',
                'Programación con Python básico',
                'Protección de datos personales',
                'Redes y telecomunicaciones',
                'Soporte técnico y mantenimiento de computadoras',
                'Telefonía IP',
                'Testing de software',
                'UX/UI y diseño de productos digitales',
            ],
            'Textil, confección, cuero y moda' => [
                'Acabados textiles y estampado',
                'Bordado computarizado',
                'Comercialización de prendas y accesorios',
                'Confección de ropa deportiva',
                'Confección de ropa interior y lencería',
                'Confección de trajes típicos regionales',
                'Confección de uniformes escolares',
                'Confección de uniformes industriales',
                'Control de calidad textil',
                'Corte y confección',
                'Diseño de accesorios y bisutería textil',
                'Diseño de moda indígena contemporánea',
                'Diseño y patronaje de moda',
                'Escalado de tallas',
                'Estampado por sublimación',
                'Gestión de producción textil',
                'Marroquinería y calzado',
                'Moda sostenible y economía circular',
                'Operación de máquinas de coser industriales',
                'Patronaje digital',
                'Producción de jeans y denim',
                'Reparación y ajuste de prendas',
                'Sastrería y alta costura',
                'Serigrafía textil',
                'Tejidos, bordados y crochet',
                'Tendido y corte industrial',
                'Teñido artesanal y natural',
                'Upcycling textil',
            ],
            'Turismo, hotelería y eventos' => [
                'Agencias de viaje y paquetes turísticos',
                'Atención a cruceristas',
                'Diseño de paquetes turísticos',
                'Diseño de rutas turísticas locales',
                'Gestión de alojamientos familiares',
                'Gestión de destinos turísticos',
                'Gestión hotelera',
                'Guianza en centros históricos',
                'Guianza turística',
                'Idiomas para turismo',
                'Interpretación ambiental',
                'Operación de hostales y pequeños hoteles',
                'Organización de eventos',
                'Protocolo y atención al visitante',
                'Recepción bilingüe',
                'Recepción y reservas',
                'Reservas en plataformas digitales',
                'Restaurantes y servicio de mesa',
                'Seguridad para actividades turísticas',
                'Servicio de habitaciones y housekeeping',
                'Turismo arqueológico y patrimonial',
                'Turismo comunitario indígena',
                'Turismo de aventura',
                'Turismo de naturaleza y avistamiento de aves',
                'Turismo de playa y costa',
                'Turismo gastronómico',
                'Turismo rural cafetalero',
                'Turismo rural y de naturaleza',
                'Turismo sostenible y comunitario',
            ],
        ];

        foreach ($items as $areaNombre => $habilidades) {
            $areaId = DB::table('tbl_area_especializacion')
                ->where('nombre', $areaNombre)
                ->value('id_area_especializacion');

            if (!$areaId) {
                throw new RuntimeException(
                    "No se encontró el área de especialización: {$areaNombre}"
                );
            }

            foreach ($habilidades as $habilidad) {
                DB::table('tbl_habilidad_tecnica')->updateOrInsert(
                    [
                        'id_area_especializacion' => $areaId,
                        'nombre' => $habilidad,
                    ],
                    [
                        'descripcion' => null,
                        'activo' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                );
            }
        }
    }
}
