<?php

namespace Database\Seeders\fac;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    public function run(): void
    {
        $municipios = [
            ['id_municipio' => 0,    'id_departamento' => 15, 'id_municipio_mh' => 0,    'nombre_distrito' => 'NO ESPECIFICADO'],
            ['id_municipio' => 1,    'id_departamento' => 1,  'id_municipio_mh' => 5,    'nombre_distrito' => 'AHUACHAPAN'],
            ['id_municipio' => 2,    'id_departamento' => 1,  'id_municipio_mh' => 5,    'nombre_distrito' => 'APANECA'],
            ['id_municipio' => 3,    'id_departamento' => 1,  'id_municipio_mh' => 4,    'nombre_distrito' => 'ATIQUIZAYA'],
            ['id_municipio' => 4,    'id_departamento' => 1,  'id_municipio_mh' => 5,    'nombre_distrito' => 'CONCEPCION ATACO'],
            ['id_municipio' => 5,    'id_departamento' => 1,  'id_municipio_mh' => 4,    'nombre_distrito' => 'EL REFUGIO'],
            ['id_municipio' => 6,    'id_departamento' => 1,  'id_municipio_mh' => 7,    'nombre_distrito' => 'GUAYMANGO'],
            ['id_municipio' => 7,    'id_departamento' => 1,  'id_municipio_mh' => 7,    'nombre_distrito' => 'JUJUTLA'],
            ['id_municipio' => 8,    'id_departamento' => 1,  'id_municipio_mh' => 7,    'nombre_distrito' => 'SAN FRANCISCO MENENDEZ'],
            ['id_municipio' => 9,    'id_departamento' => 1,  'id_municipio_mh' => 4,    'nombre_distrito' => 'SAN LORENZO'],
            ['id_municipio' => 10,   'id_departamento' => 1,  'id_municipio_mh' => 7,    'nombre_distrito' => 'SAN PEDRO PUXTLA'],
            ['id_municipio' => 11,   'id_departamento' => 1,  'id_municipio_mh' => 5,    'nombre_distrito' => 'TACUBA'],
            ['id_municipio' => 12,   'id_departamento' => 1,  'id_municipio_mh' => 4,    'nombre_distrito' => 'TURIN'],
            ['id_municipio' => 13,   'id_departamento' => 2,  'id_municipio_mh' => 10,   'nombre_distrito' => 'CANDELARIA DE LA FRONTERA'],
            ['id_municipio' => 14,   'id_departamento' => 2,  'id_municipio_mh' => 9,    'nombre_distrito' => 'COATEPEQUE'],
            ['id_municipio' => 15,   'id_departamento' => 2,  'id_municipio_mh' => 10,   'nombre_distrito' => 'CHALCHUAPA'],
            ['id_municipio' => 16,   'id_departamento' => 2,  'id_municipio_mh' => 9,    'nombre_distrito' => 'EL CONGO'],
            ['id_municipio' => 17,   'id_departamento' => 2,  'id_municipio_mh' => 10,   'nombre_distrito' => 'EL PORVENIR'],
            ['id_municipio' => 18,   'id_departamento' => 2,  'id_municipio_mh' => 6,    'nombre_distrito' => 'MASAHUAT'],
            ['id_municipio' => 19,   'id_departamento' => 2,  'id_municipio_mh' => 6,    'nombre_distrito' => 'METAPAN'],
            ['id_municipio' => 20,   'id_departamento' => 2,  'id_municipio_mh' => 10,   'nombre_distrito' => 'SAN ANTONIO PAJONAL'],
            ['id_municipio' => 21,   'id_departamento' => 2,  'id_municipio_mh' => 10,   'nombre_distrito' => 'SAN SEBASTIAN SALITRILLO'],
            ['id_municipio' => 22,   'id_departamento' => 2,  'id_municipio_mh' => 8,    'nombre_distrito' => 'SANTA ANA'],
            ['id_municipio' => 23,   'id_departamento' => 2,  'id_municipio_mh' => 6,    'nombre_distrito' => 'SANTA ROSA GUACHIPILIN'],
            ['id_municipio' => 24,   'id_departamento' => 2,  'id_municipio_mh' => 10,   'nombre_distrito' => 'SANTIAGO DE LA FRONTERA'],
            ['id_municipio' => 25,   'id_departamento' => 2,  'id_municipio_mh' => 6,    'nombre_distrito' => 'TEXISTEPEQUE'],
            ['id_municipio' => 26,   'id_departamento' => 3,  'id_municipio_mh' => 16,   'nombre_distrito' => 'ACAJUTLA'],
            ['id_municipio' => 27,   'id_departamento' => 3,  'id_municipio_mh' => 15,   'nombre_distrito' => 'ARMENIA'],
            ['id_municipio' => 28,   'id_departamento' => 3,  'id_municipio_mh' => 15,   'nombre_distrito' => 'CALUCO'],
            ['id_municipio' => 29,   'id_departamento' => 3,  'id_municipio_mh' => 15,   'nombre_distrito' => 'CUISNAHUAT'],
            ['id_municipio' => 30,   'id_departamento' => 3,  'id_municipio_mh' => 15,   'nombre_distrito' => 'SANTA ISABEL ISHUATAN'],
            ['id_municipio' => 31,   'id_departamento' => 3,  'id_municipio_mh' => 15,   'nombre_distrito' => 'IZALCO'],
            ['id_municipio' => 32,   'id_departamento' => 3,  'id_municipio_mh' => 11,   'nombre_distrito' => 'JUAYUA'],
            ['id_municipio' => 33,   'id_departamento' => 3,  'id_municipio_mh' => 11,   'nombre_distrito' => 'NAHUIZALCO'],
            ['id_municipio' => 34,   'id_departamento' => 3,  'id_municipio_mh' => 13,   'nombre_distrito' => 'NAHUILINGO'],
            ['id_municipio' => 35,   'id_departamento' => 3,  'id_municipio_mh' => 11,   'nombre_distrito' => 'SALCOATITAN'],
            ['id_municipio' => 36,   'id_departamento' => 3,  'id_municipio_mh' => 13,   'nombre_distrito' => 'SAN ANTONIO DEL MONTE'],
            ['id_municipio' => 37,   'id_departamento' => 3,  'id_municipio_mh' => 15,   'nombre_distrito' => 'SAN JULIAN'],
            ['id_municipio' => 38,   'id_departamento' => 3,  'id_municipio_mh' => 11,   'nombre_distrito' => 'SANTA CATARINA MASAHUAT'],
            ['id_municipio' => 39,   'id_departamento' => 3,  'id_municipio_mh' => 13,   'nombre_distrito' => 'SANTO DOMINGO DE GUZMAN'],
            ['id_municipio' => 40,   'id_departamento' => 3,  'id_municipio_mh' => 13,   'nombre_distrito' => 'SONSONATE'],
            ['id_municipio' => 41,   'id_departamento' => 3,  'id_municipio_mh' => 13,   'nombre_distrito' => 'SONZACATE'],
            ['id_municipio' => 42,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'AGUA CALIENTE'],
            ['id_municipio' => 43,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'ARCATAO'],
            ['id_municipio' => 44,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'AZACUALPA'],
            ['id_municipio' => 45,   'id_departamento' => 4,  'id_municipio_mh' => 31,   'nombre_distrito' => 'CITALA'],
            ['id_municipio' => 46,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'COMALAPA'],
            ['id_municipio' => 47,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'CONCEPCION QUEZALTEPEQUE'],
            ['id_municipio' => 48,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'CHALATENANGO'],
            ['id_municipio' => 49,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'DULCE NOMBRE_distrito DE MARIA'],
            ['id_municipio' => 50,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'EL CARRIZAL'],
            ['id_municipio' => 51,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'EL PARAISO'],
            ['id_municipio' => 52,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'LA LAGUNA'],
            ['id_municipio' => 53,   'id_departamento' => 4,  'id_municipio_mh' => 31,   'nombre_distrito' => 'LA PALMA'],
            ['id_municipio' => 54,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'LA REINA'],
            ['id_municipio' => 55,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'LAS VUELTAS'],
            ['id_municipio' => 56,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'NOMBRE_distrito DE JESUS'],
            ['id_municipio' => 57,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'NUEVA CONCEPCION'],
            ['id_municipio' => 58,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'NUEVA TRINIDAD'],
            ['id_municipio' => 59,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'OJOS DE AGUA'],
            ['id_municipio' => 60,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'POTONICO'],
            ['id_municipio' => 61,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'SAN ANTONIO DE LA CRUZ'],
            ['id_municipio' => 62,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'SAN ANTONIO LOS RANCHOS'],
            ['id_municipio' => 63,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'SAN FERNANDO'],
            ['id_municipio' => 64,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'SAN FRANCISCO LEMPA'],
            ['id_municipio' => 65,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'SAN FRANCISCO MORAZAN'],
            ['id_municipio' => 66,   'id_departamento' => 4,  'id_municipio_mh' => 31,   'nombre_distrito' => 'SAN IGNACIO'],
            ['id_municipio' => 67,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'SAN ISIDRO LABRADOR'],
            ['id_municipio' => 68,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'SAN JOSE CANCASQUE'],
            ['id_municipio' => 69,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'SAN JOSE LAS FLORES'],
            ['id_municipio' => 70,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'SAN LUIS DEL CARMEN'],
            ['id_municipio' => 71,   'id_departamento' => 4,  'id_municipio_mh' => 33,   'nombre_distrito' => 'SAN MIGUEL DE MERCEDES'],
            ['id_municipio' => 72,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'SAN RAFAEL'],
            ['id_municipio' => 73,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'SANTA RITA'],
            ['id_municipio' => 74,   'id_departamento' => 4,  'id_municipio_mh' => 32,   'nombre_distrito' => 'TEJUTLA'],
            ['id_municipio' => 75,   'id_departamento' => 5,  'id_municipio_mh' => 28,   'nombre_distrito' => 'ANTIGUO CUSCATLAN'],
            ['id_municipio' => 76,   'id_departamento' => 5,  'id_municipio_mh' => 23,   'nombre_distrito' => 'CIUDAD ARCE'],
            ['id_municipio' => 77,   'id_departamento' => 5,  'id_municipio_mh' => 26,   'nombre_distrito' => 'COLON'],
            ['id_municipio' => 78,   'id_departamento' => 5,  'id_municipio_mh' => 30,   'nombre_distrito' => 'COMASAGUA'],
            ['id_municipio' => 79,   'id_departamento' => 5,  'id_municipio_mh' => 29,   'nombre_distrito' => 'CHILTIUPAN'],
            ['id_municipio' => 80,   'id_departamento' => 5,  'id_municipio_mh' => 28,   'nombre_distrito' => 'HUIZUCAR'],
            ['id_municipio' => 81,   'id_departamento' => 5,  'id_municipio_mh' => 26,   'nombre_distrito' => 'JAYAQUE'],
            ['id_municipio' => 82,   'id_departamento' => 5,  'id_municipio_mh' => 28,   'nombre_distrito' => 'NUEVO CUSCATLAN'],
            ['id_municipio' => 83,   'id_departamento' => 5,  'id_municipio_mh' => 20,   'nombre_distrito' => 'QUEZALTEPEQUE'],
            ['id_municipio' => 84,   'id_departamento' => 5,  'id_municipio_mh' => 26,   'nombre_distrito' => 'SACACOYO'],
            ['id_municipio' => 85,   'id_departamento' => 5,  'id_municipio_mh' => 28,   'nombre_distrito' => 'SAN JOSE VILLANUEVA'],
            ['id_municipio' => 86,   'id_departamento' => 5,  'id_municipio_mh' => 23,   'nombre_distrito' => 'SAN JUAN OPICO'],
            ['id_municipio' => 87,   'id_departamento' => 5,  'id_municipio_mh' => 20,   'nombre_distrito' => 'SAN MATIAS'],
            ['id_municipio' => 88,   'id_departamento' => 5,  'id_municipio_mh' => 20,   'nombre_distrito' => 'SAN PABLO TACACHICO'],
            ['id_municipio' => 89,   'id_departamento' => 5,  'id_municipio_mh' => 29,   'nombre_distrito' => 'TAMANIQUE'],
            ['id_municipio' => 90,   'id_departamento' => 5,  'id_municipio_mh' => 26,   'nombre_distrito' => 'TALNIQUE'],
            ['id_municipio' => 91,   'id_departamento' => 5,  'id_municipio_mh' => 29,   'nombre_distrito' => 'TEOTEPEQUE'],
            ['id_municipio' => 92,   'id_departamento' => 5,  'id_municipio_mh' => 26,   'nombre_distrito' => 'TEPECOYO'],
            ['id_municipio' => 93,   'id_departamento' => 5,  'id_municipio_mh' => 28,   'nombre_distrito' => 'ZARAGOZA'],
            ['id_municipio' => 94,   'id_departamento' => 5,  'id_municipio_mh' => 29,   'nombre_distrito' => 'JICALAPA'],
            ['id_municipio' => 95,   'id_departamento' => 5,  'id_municipio_mh' => 29,   'nombre_distrito' => 'LA LIBERTAD'],
            ['id_municipio' => 96,   'id_departamento' => 5,  'id_municipio_mh' => 30,   'nombre_distrito' => 'SANTA TECLA'],
            ['id_municipio' => 97,   'id_departamento' => 6,  'id_municipio_mh' => 17,   'nombre_distrito' => 'AGUILARES'],
            ['id_municipio' => 98,   'id_departamento' => 6,  'id_municipio_mh' => 18,   'nombre_distrito' => 'APOPA'],
            ['id_municipio' => 99,   'id_departamento' => 6,  'id_municipio_mh' => 21,   'nombre_distrito' => 'AYUTUXTEPEQUE'],
            ['id_municipio' => 100,  'id_departamento' => 6,  'id_municipio_mh' => 21,   'nombre_distrito' => 'CUSCATANCINGO'],
            ['id_municipio' => 101,  'id_departamento' => 6,  'id_municipio_mh' => 21,   'nombre_distrito' => 'CIUDAD DELGADO'],
            ['id_municipio' => 102,  'id_departamento' => 6,  'id_municipio_mh' => 17,   'nombre_distrito' => 'EL PAISNAL'],
            ['id_municipio' => 103,  'id_departamento' => 6,  'id_municipio_mh' => 17,   'nombre_distrito' => 'GUAZAPA'],
            ['id_municipio' => 104,  'id_departamento' => 6,  'id_municipio_mh' => 19,   'nombre_distrito' => 'ILOPANGO'],
            ['id_municipio' => 105,  'id_departamento' => 6,  'id_municipio_mh' => 21,   'nombre_distrito' => 'MEJICANOS'],
            ['id_municipio' => 106,  'id_departamento' => 6,  'id_municipio_mh' => 18,   'nombre_distrito' => 'NEJAPA'],
            ['id_municipio' => 107,  'id_departamento' => 6,  'id_municipio_mh' => 24,   'nombre_distrito' => 'PANCHIMALCO'],
            ['id_municipio' => 108,  'id_departamento' => 6,  'id_municipio_mh' => 24,   'nombre_distrito' => 'ROSARIO DE MORA'],
            ['id_municipio' => 109,  'id_departamento' => 6,  'id_municipio_mh' => 24,   'nombre_distrito' => 'SAN MARCOS'],
            ['id_municipio' => 110,  'id_departamento' => 6,  'id_municipio_mh' => 19,   'nombre_distrito' => 'SAN MARTIN'],
            ['id_municipio' => 111,  'id_departamento' => 6,  'id_municipio_mh' => 21,   'nombre_distrito' => 'SAN SALVADOR'],
            ['id_municipio' => 112,  'id_departamento' => 6,  'id_municipio_mh' => 24,   'nombre_distrito' => 'SANTIAGO TEXACUANGOS'],
            ['id_municipio' => 113,  'id_departamento' => 6,  'id_municipio_mh' => 24,   'nombre_distrito' => 'SANTO TOMAS'],
            ['id_municipio' => 114,  'id_departamento' => 6,  'id_municipio_mh' => 19,   'nombre_distrito' => 'SOYAPANGO'],
            ['id_municipio' => 115,  'id_departamento' => 6,  'id_municipio_mh' => 19,   'nombre_distrito' => 'TONACATEPEQUE'],
            ['id_municipio' => 116,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'CANDELARIA'],
            ['id_municipio' => 117,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'COJUTEPEQUE'],
            ['id_municipio' => 118,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'EL CARMEN'],
            ['id_municipio' => 119,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'EL ROSARIO'],
            ['id_municipio' => 120,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'MONTE DE SAN JUAN'],
            ['id_municipio' => 121,  'id_departamento' => 7,  'id_municipio_mh' => 12,   'nombre_distrito' => 'ORATORIO DE CONCEPCION'],
            ['id_municipio' => 122,  'id_departamento' => 7,  'id_municipio_mh' => 12,   'nombre_distrito' => 'SAN BARTOLOME PERULAPIA'],
            ['id_municipio' => 123,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'SAN CRISTOBAL'],
            ['id_municipio' => 124,  'id_departamento' => 7,  'id_municipio_mh' => 12,   'nombre_distrito' => 'SAN JOSE GUAYABAL'],
            ['id_municipio' => 125,  'id_departamento' => 7,  'id_municipio_mh' => 12,   'nombre_distrito' => 'SAN PEDRO PERULAPAN'],
            ['id_municipio' => 126,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'SAN RAFAEL CEDROS'],
            ['id_municipio' => 127,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'SAN RAMON'],
            ['id_municipio' => 128,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'SANTA CRUZ ANALQUITO'],
            ['id_municipio' => 129,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'SANTA CRUZ MICHAPA'],
            ['id_municipio' => 130,  'id_departamento' => 7,  'id_municipio_mh' => 12,   'nombre_distrito' => 'SUCHITOTO'],
            ['id_municipio' => 131,  'id_departamento' => 7,  'id_municipio_mh' => 14,   'nombre_distrito' => 'TENANCINGO'],
            ['id_municipio' => 132,  'id_departamento' => 8,  'id_municipio_mh' => 22,   'nombre_distrito' => 'CUYULTITAN'],
            ['id_municipio' => 133,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'EL ROSARIO'],
            ['id_municipio' => 134,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'JERUSALEN'],
            ['id_municipio' => 135,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'MERCEDES LA CEIBA'],
            ['id_municipio' => 136,  'id_departamento' => 8,  'id_municipio_mh' => 22,   'nombre_distrito' => 'OLOCUILTA'],
            ['id_municipio' => 137,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'PARAISO DE OSORIO'],
            ['id_municipio' => 138,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'SAN ANTONIO MASAHUAT'],
            ['id_municipio' => 139,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'SAN EMIGDIO'],
            ['id_municipio' => 140,  'id_departamento' => 8,  'id_municipio_mh' => 22,   'nombre_distrito' => 'SAN FRANCISCO CHINAMECA'],
            ['id_municipio' => 141,  'id_departamento' => 8,  'id_municipio_mh' => 27,   'nombre_distrito' => 'SAN JUAN NONUALCO'],
            ['id_municipio' => 142,  'id_departamento' => 8,  'id_municipio_mh' => 22,   'nombre_distrito' => 'SAN JUAN TALPA'],
            ['id_municipio' => 143,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'SAN JUAN TEPEZONTES'],
            ['id_municipio' => 144,  'id_departamento' => 8,  'id_municipio_mh' => 22,   'nombre_distrito' => 'SAN LUIS TALPA'],
            ['id_municipio' => 145,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'SAN LUIS LA HERRADURA'],
            ['id_municipio' => 146,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'SAN MIGUEL TEPEZONTES'],
            ['id_municipio' => 147,  'id_departamento' => 8,  'id_municipio_mh' => 22,   'nombre_distrito' => 'SAN PEDRO MASAHUAT'],
            ['id_municipio' => 148,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'SAN PEDRO NONUALCO'],
            ['id_municipio' => 149,  'id_departamento' => 8,  'id_municipio_mh' => 27,   'nombre_distrito' => 'SAN RAFAEL OBRAJUELO'],
            ['id_municipio' => 150,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'SANTA MARIA OSTUMA'],
            ['id_municipio' => 151,  'id_departamento' => 8,  'id_municipio_mh' => 25,   'nombre_distrito' => 'SANTIAGO NONUALCO'],
            ['id_municipio' => 152,  'id_departamento' => 8,  'id_municipio_mh' => 22,   'nombre_distrito' => 'TAPALHUACA'],
            ['id_municipio' => 153,  'id_departamento' => 8,  'id_municipio_mh' => 27,   'nombre_distrito' => 'ZACATECOLUCA'],
            ['id_municipio' => 154,  'id_departamento' => 9,  'id_municipio_mh' => 2,    'nombre_distrito' => 'CINQUERA'],
            ['id_municipio' => 155,  'id_departamento' => 9,  'id_municipio_mh' => 2,    'nombre_distrito' => 'ILOBASCO'],
            ['id_municipio' => 156,  'id_departamento' => 9,  'id_municipio_mh' => 2,    'nombre_distrito' => 'JUTIAPA'],
            ['id_municipio' => 157,  'id_departamento' => 9,  'id_municipio_mh' => 3,    'nombre_distrito' => 'SAN ISIDRO'],
            ['id_municipio' => 158,  'id_departamento' => 9,  'id_municipio_mh' => 3,    'nombre_distrito' => 'SENSUNTEPEQUE'],
            ['id_municipio' => 159,  'id_departamento' => 9,  'id_municipio_mh' => 2,    'nombre_distrito' => 'TEJUTEPEQUE'],
            ['id_municipio' => 160,  'id_departamento' => 9,  'id_municipio_mh' => 3,    'nombre_distrito' => 'VILLA VICTORIA'],
            ['id_municipio' => 161,  'id_departamento' => 9,  'id_municipio_mh' => 3,    'nombre_distrito' => 'VILLA DOLORES'],
            ['id_municipio' => 162,  'id_departamento' => 9,  'id_municipio_mh' => 3,    'nombre_distrito' => 'GUACOTECTI'],
            ['id_municipio' => 163,  'id_departamento' => 10, 'id_municipio_mh' => 34,   'nombre_distrito' => 'APASTEPEQUE'],
            ['id_municipio' => 164,  'id_departamento' => 10, 'id_municipio_mh' => 42,   'nombre_distrito' => 'GUADALUPE'],
            ['id_municipio' => 165,  'id_departamento' => 10, 'id_municipio_mh' => 42,   'nombre_distrito' => 'SAN CAYETANO ISTEPEQUE'],
            ['id_municipio' => 166,  'id_departamento' => 10, 'id_municipio_mh' => 34,   'nombre_distrito' => 'SANTA CLARA'],
            ['id_municipio' => 167,  'id_departamento' => 10, 'id_municipio_mh' => 34,   'nombre_distrito' => 'SANTO DOMINGO'],
            ['id_municipio' => 168,  'id_departamento' => 10, 'id_municipio_mh' => 34,   'nombre_distrito' => 'SAN ESTEBAN CATARINA'],
            ['id_municipio' => 169,  'id_departamento' => 10, 'id_municipio_mh' => 34,   'nombre_distrito' => 'SAN ILDEFONSO'],
            ['id_municipio' => 170,  'id_departamento' => 10, 'id_municipio_mh' => 34,   'nombre_distrito' => 'SAN LORENZO'],
            ['id_municipio' => 171,  'id_departamento' => 10, 'id_municipio_mh' => 34,   'nombre_distrito' => 'SAN SEBASTIAN'],
            ['id_municipio' => 172,  'id_departamento' => 10, 'id_municipio_mh' => 42,   'nombre_distrito' => 'SAN VICENTE'],
            ['id_municipio' => 173,  'id_departamento' => 10, 'id_municipio_mh' => 42,   'nombre_distrito' => 'TECOLUCA'],
            ['id_municipio' => 174,  'id_departamento' => 10, 'id_municipio_mh' => 42,   'nombre_distrito' => 'TEPETITAN'],
            ['id_municipio' => 175,  'id_departamento' => 10, 'id_municipio_mh' => 42,   'nombre_distrito' => 'VERAPAZ'],
            ['id_municipio' => 176,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'ALEGRIA'],
            ['id_municipio' => 177,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'BERLIN'],
            ['id_municipio' => 178,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'CALIFORNIA'],
            ['id_municipio' => 179,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'CONCEPCION BATRES'],
            ['id_municipio' => 180,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'EL TRIUNFO'],
            ['id_municipio' => 181,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'EREGUAYQUIN'],
            ['id_municipio' => 182,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'ESTANZUELAS'],
            ['id_municipio' => 183,  'id_departamento' => 11, 'id_municipio_mh' => 45,   'nombre_distrito' => 'JIQUILISCO'],
            ['id_municipio' => 184,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'JUCUAPA'],
            ['id_municipio' => 185,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'JUCUARAN'],
            ['id_municipio' => 186,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'MERCEDES UMAÑA'],
            ['id_municipio' => 187,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'NUEVA GRANADA'],
            ['id_municipio' => 188,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'OZATLAN'],
            ['id_municipio' => 189,  'id_departamento' => 11, 'id_municipio_mh' => 45,   'nombre_distrito' => 'PUERTO EL TRIUNFO'],
            ['id_municipio' => 190,  'id_departamento' => 11, 'id_municipio_mh' => 45,   'nombre_distrito' => 'SAN AGUSTIN'],
            ['id_municipio' => 191,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'SAN BUENAVENTURA'],
            ['id_municipio' => 192,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'SAN DIONICIO'],
            ['id_municipio' => 193,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'SANTA ELENA'],
            ['id_municipio' => 194,  'id_departamento' => 11, 'id_municipio_mh' => 45,   'nombre_distrito' => 'SAN FRANCISCO JAVIER'],
            ['id_municipio' => 195,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'SANTA MARIA'],
            ['id_municipio' => 196,  'id_departamento' => 11, 'id_municipio_mh' => 44,   'nombre_distrito' => 'SANTIAGO DE MARIA'],
            ['id_municipio' => 197,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'TECAPAN'],
            ['id_municipio' => 198,  'id_departamento' => 11, 'id_municipio_mh' => 43,   'nombre_distrito' => 'USULUTAN'],
            ['id_municipio' => 199,  'id_departamento' => 12, 'id_municipio_mh' => 40,   'nombre_distrito' => 'CAROLINA'],
            ['id_municipio' => 200,  'id_departamento' => 12, 'id_municipio_mh' => 40,   'nombre_distrito' => 'CIUDAD BARRIOS'],
            ['id_municipio' => 201,  'id_departamento' => 12, 'id_municipio_mh' => 39,   'nombre_distrito' => 'COMACARAN'],
            ['id_municipio' => 202,  'id_departamento' => 12, 'id_municipio_mh' => 40,   'nombre_distrito' => 'CHAPELTIQUE'],
            ['id_municipio' => 203,  'id_departamento' => 12, 'id_municipio_mh' => 41,   'nombre_distrito' => 'CHINAMECA'],
            ['id_municipio' => 204,  'id_departamento' => 12, 'id_municipio_mh' => 39,   'nombre_distrito' => 'CHIRILAGUA'],
            ['id_municipio' => 205,  'id_departamento' => 12, 'id_municipio_mh' => 41,   'nombre_distrito' => 'EL TRANSITO'],
            ['id_municipio' => 206,  'id_departamento' => 12, 'id_municipio_mh' => 41,   'nombre_distrito' => 'LOLOTIQUE'],
            ['id_municipio' => 207,  'id_departamento' => 12, 'id_municipio_mh' => 39,   'nombre_distrito' => 'MONCAGUA'],
            ['id_municipio' => 208,  'id_departamento' => 12, 'id_municipio_mh' => 41,   'nombre_distrito' => 'NUEVA GUADALUPE'],
            ['id_municipio' => 209,  'id_departamento' => 12, 'id_municipio_mh' => 40,   'nombre_distrito' => 'NUEVO EDEN DE SAN JUAN'],
            ['id_municipio' => 210,  'id_departamento' => 12, 'id_municipio_mh' => 39,   'nombre_distrito' => 'QUELEPA'],
            ['id_municipio' => 211,  'id_departamento' => 12, 'id_municipio_mh' => 40,   'nombre_distrito' => 'SAN ANTONIO DEL MOSCO'],
            ['id_municipio' => 212,  'id_departamento' => 12, 'id_municipio_mh' => 40,   'nombre_distrito' => 'SAN GERARDO'],
            ['id_municipio' => 213,  'id_departamento' => 12, 'id_municipio_mh' => 41,   'nombre_distrito' => 'SAN JORGE'],
            ['id_municipio' => 214,  'id_departamento' => 12, 'id_municipio_mh' => 40,   'nombre_distrito' => 'SAN LUIS DE LA REINA'],
            ['id_municipio' => 215,  'id_departamento' => 12, 'id_municipio_mh' => 39,   'nombre_distrito' => 'SAN MIGUEL'],
            ['id_municipio' => 216,  'id_departamento' => 12, 'id_municipio_mh' => 41,   'nombre_distrito' => 'SAN RAFAEL ORIENTE'],
            ['id_municipio' => 217,  'id_departamento' => 12, 'id_municipio_mh' => 40,   'nombre_distrito' => 'SESORI'],
            ['id_municipio' => 218,  'id_departamento' => 12, 'id_municipio_mh' => 39,   'nombre_distrito' => 'ULUAZAPA'],
            ['id_municipio' => 219,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'ARAMBALA'],
            ['id_municipio' => 220,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'CACAOPERA'],
            ['id_municipio' => 221,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'CORINTO'],
            ['id_municipio' => 222,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'CHILANGA'],
            ['id_municipio' => 223,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'DELICIAS DE CONCEPCION'],
            ['id_municipio' => 224,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'EL DIVISADERO'],
            ['id_municipio' => 225,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'EL ROSARIO'],
            ['id_municipio' => 226,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'GUALOCOCTI'],
            ['id_municipio' => 227,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'GUATAJIAGUA'],
            ['id_municipio' => 228,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'JOATECA'],
            ['id_municipio' => 229,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'JOCOAITIQUE'],
            ['id_municipio' => 230,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'JOCORO'],
            ['id_municipio' => 231,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'LOLOTIQUILLO'],
            ['id_municipio' => 232,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'MEANGUERA'],
            ['id_municipio' => 233,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'OSCICALA'],
            ['id_municipio' => 234,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'PERQUIN'],
            ['id_municipio' => 235,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'SAN CARLOS'],
            ['id_municipio' => 236,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'SAN FERNANDO'],
            ['id_municipio' => 237,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'SAN FRANCISCO GOTERA'],
            ['id_municipio' => 238,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'SAN ISIDRO'],
            ['id_municipio' => 239,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'SAN SIMON'],
            ['id_municipio' => 240,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'SENSEMBRA'],
            ['id_municipio' => 241,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'SOCIEDAD'],
            ['id_municipio' => 242,  'id_departamento' => 13, 'id_municipio_mh' => 37,   'nombre_distrito' => 'TOROLA'],
            ['id_municipio' => 243,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'YAMABAL'],
            ['id_municipio' => 244,  'id_departamento' => 13, 'id_municipio_mh' => 38,   'nombre_distrito' => 'YOLOAIQUIN'],
            ['id_municipio' => 245,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'ANAMOROS'],
            ['id_municipio' => 246,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'BOLIVAR'],
            ['id_municipio' => 247,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'CONCEPCION DE ORIENTE'],
            ['id_municipio' => 248,  'id_departamento' => 14, 'id_municipio_mh' => 36,   'nombre_distrito' => 'CONCHAGUA'],
            ['id_municipio' => 249,  'id_departamento' => 14, 'id_municipio_mh' => 36,   'nombre_distrito' => 'EL CARMEN'],
            ['id_municipio' => 250,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'EL SAUCE'],
            ['id_municipio' => 251,  'id_departamento' => 14, 'id_municipio_mh' => 36,   'nombre_distrito' => 'INTIPUCA'],
            ['id_municipio' => 252,  'id_departamento' => 14, 'id_municipio_mh' => 36,   'nombre_distrito' => 'LA UNION'],
            ['id_municipio' => 253,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'LISLIQUE'],
            ['id_municipio' => 254,  'id_departamento' => 14, 'id_municipio_mh' => 36,   'nombre_distrito' => 'MEANGUERA DEL GOLFO'],
            ['id_municipio' => 255,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'NUEVA ESPARTA'],
            ['id_municipio' => 256,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'PASAQUINA'],
            ['id_municipio' => 257,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'POLOROS'],
            ['id_municipio' => 258,  'id_departamento' => 14, 'id_municipio_mh' => 36,   'nombre_distrito' => 'SAN ALEJO'],
            ['id_municipio' => 259,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'SAN JOSE'],
            ['id_municipio' => 260,  'id_departamento' => 14, 'id_municipio_mh' => 35,   'nombre_distrito' => 'SANTA ROSA DE LIMA'],
            ['id_municipio' => 261,  'id_departamento' => 14, 'id_municipio_mh' => 36,   'nombre_distrito' => 'YAYANTIQUE'],
            ['id_municipio' => 262,  'id_departamento' => 14, 'id_municipio_mh' => 36,   'nombre_distrito' => 'YUCUAIQUIN'],
            ['id_municipio' => 263,  'id_departamento' => 24, 'id_municipio_mh' => null,  'nombre_distrito' => 'MIAMI'],
            ['id_municipio' => 264,  'id_departamento' => 25, 'id_municipio_mh' => null,  'nombre_distrito' => 'QUITO'],
            ['id_municipio' => 2000, 'id_departamento' => 18, 'id_municipio_mh' => 0,    'nombre_distrito' => 'TEGUCIGALPA'],
            ['id_municipio' => 2001, 'id_departamento' => 23, 'id_municipio_mh' => null,  'nombre_distrito' => 'LOS ANGELES'],
            ['id_municipio' => 2002, 'id_departamento' => 21, 'id_municipio_mh' => null,  'nombre_distrito' => 'ILLINOIS'],
            ['id_municipio' => 2003, 'id_departamento' => 16, 'id_municipio_mh' => null,  'nombre_distrito' => 'GENÉRICO'],
            ['id_municipio' => 2004, 'id_departamento' => 29, 'id_municipio_mh' => 0,    'nombre_distrito' => 'EL SALVADOR NO DEFINIDO'],
            ['id_municipio' => 2005, 'id_departamento' => 22, 'id_municipio_mh' => null,  'nombre_distrito' => 'GUATEMALA'],
            ['id_municipio' => 2006, 'id_departamento' => 6,  'id_municipio_mh' => 0,    'nombre_distrito' => 'SAN JACINTO'],
            ['id_municipio' => 2007, 'id_departamento' => 31, 'id_municipio_mh' => null,  'nombre_distrito' => 'COSTA RICA'],
            ['id_municipio' => 2008, 'id_departamento' => 33, 'id_municipio_mh' => null,  'nombre_distrito' => 'ESTADOS UNIDOS'],
            ['id_municipio' => 2009, 'id_departamento' => 34, 'id_municipio_mh' => null,  'nombre_distrito' => 'LUXEMBURGO'],
            ['id_municipio' => 2010, 'id_departamento' => 35, 'id_municipio_mh' => null,  'nombre_distrito' => 'PUEBLA'],
            ['id_municipio' => 2011, 'id_departamento' => 36, 'id_municipio_mh' => null,  'nombre_distrito' => 'REPUBLICA DOMINICANA'],
            ['id_municipio' => 2012, 'id_departamento' => 4,  'id_municipio_mh' => 0,    'nombre_distrito' => 'QUEZALTEPEQUE'],
            ['id_municipio' => 2013, 'id_departamento' => 39, 'id_municipio_mh' => null,  'nombre_distrito' => 'BERLIN'],
            ['id_municipio' => 2014, 'id_departamento' => 32, 'id_municipio_mh' => null,  'nombre_distrito' => 'BOGOTA'],
            ['id_municipio' => 2015, 'id_departamento' => 20, 'id_municipio_mh' => null,  'nombre_distrito' => 'MEXICO DF'],
            ['id_municipio' => 2016, 'id_departamento' => 40, 'id_municipio_mh' => null,  'nombre_distrito' => 'ITALIA'],
            ['id_municipio' => 2017, 'id_departamento' => 17, 'id_municipio_mh' => null,  'nombre_distrito' => 'BRASIL NO DEFINIDO'],
            ['id_municipio' => 2018, 'id_departamento' => 18, 'id_municipio_mh' => null,  'nombre_distrito' => 'CANADA NO DEFINIDO'],
            ['id_municipio' => 2019, 'id_departamento' => 19, 'id_municipio_mh' => null,  'nombre_distrito' => 'JAPON NO DEFINIDO'],
            ['id_municipio' => 2020, 'id_departamento' => 26, 'id_municipio_mh' => null,  'nombre_distrito' => 'HONDURAS'],
            ['id_municipio' => 2021, 'id_departamento' => 27, 'id_municipio_mh' => null,  'nombre_distrito' => 'HONDURAS'],
            ['id_municipio' => 2022, 'id_departamento' => 28, 'id_municipio_mh' => null,  'nombre_distrito' => 'VENEZUELA'],
            ['id_municipio' => 2023, 'id_departamento' => 30, 'id_municipio_mh' => null,  'nombre_distrito' => 'NICARAGUA'],
            ['id_municipio' => 2024, 'id_departamento' => 37, 'id_municipio_mh' => null,  'nombre_distrito' => 'PANAMÁ'],
            ['id_municipio' => 2025, 'id_departamento' => 38, 'id_municipio_mh' => null,  'nombre_distrito' => 'BELICE'],
            ['id_municipio' => 2026, 'id_departamento' => 41, 'id_municipio_mh' => null,  'nombre_distrito' => 'PUERTO RICO'],
            ['id_municipio' => 2027, 'id_departamento' => 42, 'id_municipio_mh' => null,  'nombre_distrito' => 'JAPON'],
            ['id_municipio' => 2028, 'id_departamento' => 43, 'id_municipio_mh' => null,  'nombre_distrito' => 'VENEZUELA'],
            ['id_municipio' => 2029, 'id_departamento' => 44, 'id_municipio_mh' => null,  'nombre_distrito' => 'BUENOS AIRES'],
            ['id_municipio' => 2030, 'id_departamento' => 45, 'id_municipio_mh' => null,  'nombre_distrito' => 'PORTUGAL'],
            ['id_municipio' => 2031, 'id_departamento' => 46, 'id_municipio_mh' => null,  'nombre_distrito' => 'HOLANDA'],
            ['id_municipio' => 2032, 'id_departamento' => 47, 'id_municipio_mh' => null,  'nombre_distrito' => 'SERBIA'],
            ['id_municipio' => 2033, 'id_departamento' => 48, 'id_municipio_mh' => null,  'nombre_distrito' => 'SUIZA'],
            ['id_municipio' => 2034, 'id_departamento' => 49, 'id_municipio_mh' => null,  'nombre_distrito' => 'ESPAÑA'],
            ['id_municipio' => 2035, 'id_departamento' => 31, 'id_municipio_mh' => null,  'nombre_distrito' => 'COSTA RICA'],
            ['id_municipio' => 2036, 'id_departamento' => 51, 'id_municipio_mh' => null,  'nombre_distrito' => 'LONDRES'],
            ['id_municipio' => 2037, 'id_departamento' => 28, 'id_municipio_mh' => null,  'nombre_distrito' => 'SAN PEDRO SULA'],
            ['id_municipio' => 2038, 'id_departamento' => 20, 'id_municipio_mh' => null,  'nombre_distrito' => 'CUAJIMALPA DE MORELOS'],
            ['id_municipio' => 2039, 'id_departamento' => 53, 'id_municipio_mh' => null,  'nombre_distrito' => 'BOLIVIA'],
            ['id_municipio' => 2040, 'id_departamento' => 54, 'id_municipio_mh' => null,  'nombre_distrito' => 'LIMA'],
            ['id_municipio' => 2041, 'id_departamento' => 55, 'id_municipio_mh' => null,  'nombre_distrito' => 'MEDELLIN'],
            ['id_municipio' => 2043, 'id_departamento' => 56, 'id_municipio_mh' => null,  'nombre_distrito' => 'MONTERREY'],
            ['id_municipio' => 2044, 'id_departamento' => 57, 'id_municipio_mh' => null,  'nombre_distrito' => 'SINGAPORE'],
            ['id_municipio' => 2045, 'id_departamento' => 58, 'id_municipio_mh' => null,  'nombre_distrito' => 'GENÉRICO'],
            ['id_municipio' => 2046, 'id_departamento' => 61, 'id_municipio_mh' => null,  'nombre_distrito' => '.'],
            ['id_municipio' => 2047, 'id_departamento' => 60, 'id_municipio_mh' => null,  'nombre_distrito' => '.'],
            ['id_municipio' => 2048, 'id_departamento' => 62, 'id_municipio_mh' => null,  'nombre_distrito' => 'BREMEN'],
            ['id_municipio' => 2049, 'id_departamento' => 63, 'id_municipio_mh' => null,  'nombre_distrito' => 'MONTEVIDEO'],
            ['id_municipio' => 2050, 'id_departamento' => 64, 'id_municipio_mh' => null,  'nombre_distrito' => 'SAN JOSE'],
            ['id_municipio' => 2051, 'id_departamento' => 65, 'id_municipio_mh' => null,  'nombre_distrito' => 'GENERICO'],
            ['id_municipio' => 2052, 'id_departamento' => 67, 'id_municipio_mh' => null,  'nombre_distrito' => 'NO ESPECIFICADO'],
        ];

        $rows = array_map(fn($m) => [
            'id_municipio'    => $m['id_municipio'],
            'id_departamento' => $m['id_departamento'],
            'id_municipio_mh' => $m['id_municipio_mh'],
            'nombre_distrito'          => $m['nombre_distrito'],
            'activo'          => true,
            'usuario_crea'    => null,
            'usuario_mod'     => null,
            'usuario_elim'    => null,
            'created_at'      => now(),
            'updated_at'      => now(),
            'deleted_at'      => null,
        ], $municipios);

        foreach (array_chunk($rows, 100) as $chunk) {
            DB::table('tbl_municipio')->insertOrIgnore($chunk);
        }
    }
}