<?php

namespace Database\Seeders\fac;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PaisSeeder extends Seeder
{
    public function run(): void
    {
        $usuarioCrea = DB::table('seg_usuarios')
            ->where('username', 'clainezr')
            ->value('id_usuario');

        $now = Carbon::today();

        $paises = [
            ['id_pais' => 1,    'nombre' => 'EL SALVADOR'],
            ['id_pais' => 2,    'nombre' => 'ESTADOS UNIDOS'],
            ['id_pais' => 3,    'nombre' => 'HONDURAS'],
            ['id_pais' => 4,    'nombre' => 'MÉXICO'],
            ['id_pais' => 5,    'nombre' => 'PUERTO RICO'],
            ['id_pais' => 7,    'nombre' => 'COSTA RICA'],
            ['id_pais' => 8,    'nombre' => 'PANAMÁ'],
            ['id_pais' => 9,    'nombre' => 'GUATEMALA'],
            ['id_pais' => 11,   'nombre' => 'CANADÁ'],
            ['id_pais' => 13,   'nombre' => 'BRASIL'],
            ['id_pais' => 17,   'nombre' => 'CHILE'],
            ['id_pais' => 19,   'nombre' => 'JAPÓN'],
            ['id_pais' => 20,   'nombre' => 'MÉXICO'],
            ['id_pais' => 26,   'nombre' => 'VENEZUELA'],
            ['id_pais' => 27,   'nombre' => 'NICARAGUA'],
            ['id_pais' => 28,   'nombre' => 'ECUADOR'],
            ['id_pais' => 29,   'nombre' => 'COLOMBIA'],
            ['id_pais' => 30,   'nombre' => 'LUXEMBURGO'],
            ['id_pais' => 31,   'nombre' => 'ARGENTINA'],
            ['id_pais' => 32,   'nombre' => 'PORTUGAL'],
            ['id_pais' => 35,   'nombre' => 'PAÍSES BAJOS'],
            ['id_pais' => 36,   'nombre' => 'SERBIA'],
            ['id_pais' => 37,   'nombre' => 'SUIZA'],
            ['id_pais' => 38,   'nombre' => 'ESPAÑA'],
            ['id_pais' => 39,   'nombre' => 'REPUBLICA DOMINICANA'],
            ['id_pais' => 40,   'nombre' => 'BELICE'],
            ['id_pais' => 41,   'nombre' => 'ALEMANIA'],
            ['id_pais' => 42,   'nombre' => 'ITALIA'],
            ['id_pais' => 43,   'nombre' => 'REINO UNIDO'],
            ['id_pais' => 44,   'nombre' => 'INGLATERRA'],
            ['id_pais' => 45,   'nombre' => 'FRANCIA'],
            ['id_pais' => 46,   'nombre' => 'BOLIVIA'],
            ['id_pais' => 47,   'nombre' => 'PERÚ'],
            ['id_pais' => 48,   'nombre' => 'URUGUAY'],
            ['id_pais' => 49,   'nombre' => 'SINGAPUR'],
            ['id_pais' => 51,   'nombre' => 'FRANCIA'],
            ['id_pais' => 52,   'nombre' => 'IRLANDA'],
            ['id_pais' => 53,   'nombre' => 'CROACIA'],
            ['id_pais' => 54,   'nombre' => 'INDIA'],
            ['id_pais' => 763,  'nombre' => 'AFGANISTÁN'],
            ['id_pais' => 764,  'nombre' => 'ALAND'],
            ['id_pais' => 765,  'nombre' => 'ALBANIA'],
            ['id_pais' => 766,  'nombre' => 'ALEMANIA OCCID'],
            ['id_pais' => 767,  'nombre' => 'ALEMANIA ORIENT'],
            ['id_pais' => 768,  'nombre' => 'ALTO VOLTA'],
            ['id_pais' => 769,  'nombre' => 'ANDORRA'],
            ['id_pais' => 770,  'nombre' => 'ANGOLA'],
            ['id_pais' => 771,  'nombre' => 'ANTIG Y BARBUDA'],
            ['id_pais' => 772,  'nombre' => 'ANGUILA'],
            ['id_pais' => 773,  'nombre' => 'ARABIA SAUDITA'],
            ['id_pais' => 774,  'nombre' => 'ARGELIA'],
            ['id_pais' => 775,  'nombre' => 'ARUBA'],
            ['id_pais' => 776,  'nombre' => 'AUSTRALIA'],
            ['id_pais' => 777,  'nombre' => 'AUSTRIA'],
            ['id_pais' => 778,  'nombre' => 'AZERBAIYÁN'],
            ['id_pais' => 779,  'nombre' => 'BANGLADESH'],
            ['id_pais' => 780,  'nombre' => 'BAHREIN'],
            ['id_pais' => 781,  'nombre' => 'BARBADOS'],
            ['id_pais' => 782,  'nombre' => 'BÉLGICA'],
            ['id_pais' => 783,  'nombre' => 'BELICE'],
            ['id_pais' => 784,  'nombre' => 'BENIN'],
            ['id_pais' => 785,  'nombre' => 'BIELORRUSIA'],
            ['id_pais' => 786,  'nombre' => 'MYANMAR'],
            ['id_pais' => 787,  'nombre' => 'BOSNIA Y HERZEGOVINA'],
            ['id_pais' => 788,  'nombre' => 'BOTSWANA'],
            ['id_pais' => 789,  'nombre' => 'BRUNEI'],
            ['id_pais' => 790,  'nombre' => 'BULGARIA'],
            ['id_pais' => 791,  'nombre' => 'BURKINA FASO'],
            ['id_pais' => 792,  'nombre' => 'BURUNDI'],
            ['id_pais' => 793,  'nombre' => 'BOPHUTHATSWANA'],
            ['id_pais' => 794,  'nombre' => 'BUTÁN'],
            ['id_pais' => 795,  'nombre' => 'CABO VERDE'],
            ['id_pais' => 796,  'nombre' => 'CAMBOYA'],
            ['id_pais' => 797,  'nombre' => 'CAMERÚN'],
            ['id_pais' => 798,  'nombre' => 'CEILAN'],
            ['id_pais' => 799,  'nombre' => 'CENTROAFRICANA, REPÚBLICA'],
            ['id_pais' => 800,  'nombre' => 'COMORAS'],
            ['id_pais' => 801,  'nombre' => 'CONGO'],
            ['id_pais' => 802,  'nombre' => 'REP. DEMOCRÁTICA POPULAR DEL CONGO'],
            ['id_pais' => 803,  'nombre' => 'REP. DEMOCRÁTICA POPULAR DE COREA DEL NORTE'],
            ['id_pais' => 804,  'nombre' => 'REPÚBLICA DE COREA'],
            ['id_pais' => 805,  'nombre' => 'COSTA DE MARFIL'],
            ['id_pais' => 806,  'nombre' => 'CUBA'],
            ['id_pais' => 807,  'nombre' => 'CHAD'],
            ['id_pais' => 808,  'nombre' => 'CHECOSLOVAQUIA'],
            ['id_pais' => 809,  'nombre' => 'CHINA'],
            ['id_pais' => 810,  'nombre' => 'CHIPRE'],
            ['id_pais' => 811,  'nombre' => 'DAHOMEY'],
            ['id_pais' => 812,  'nombre' => 'DINAMARCA'],
            ['id_pais' => 813,  'nombre' => 'DJIBOUTÍ'],
            ['id_pais' => 814,  'nombre' => 'DOMINICA'],
            ['id_pais' => 815,  'nombre' => 'EMIRATOS ÁRABES UNIDOS'],
            ['id_pais' => 816,  'nombre' => 'ESLOVAQUIA'],
            ['id_pais' => 817,  'nombre' => 'ESLOVENIA'],
            ['id_pais' => 818,  'nombre' => 'ETIOPÍA'],
            ['id_pais' => 819,  'nombre' => 'ERITREA'],
            ['id_pais' => 820,  'nombre' => 'FIJI'],
            ['id_pais' => 821,  'nombre' => 'ESTONIA'],
            ['id_pais' => 822,  'nombre' => 'FILIPINAS'],
            ['id_pais' => 823,  'nombre' => 'FINLANDIA'],
            ['id_pais' => 824,  'nombre' => 'GABÓN'],
            ['id_pais' => 825,  'nombre' => 'GAMBIA'],
            ['id_pais' => 826,  'nombre' => 'GEORGIA'],
            ['id_pais' => 827,  'nombre' => 'GHANA'],
            ['id_pais' => 828,  'nombre' => 'GIBRALTAR'],
            ['id_pais' => 829,  'nombre' => 'GRECIA'],
            ['id_pais' => 830,  'nombre' => 'GRANADA'],
            ['id_pais' => 831,  'nombre' => 'GROENLANDIA'],
            ['id_pais' => 832,  'nombre' => 'GUINEA'],
            ['id_pais' => 833,  'nombre' => 'GUYANA'],
            ['id_pais' => 834,  'nombre' => 'GUADALUPE'],
            ['id_pais' => 835,  'nombre' => 'GUAM'],
            ['id_pais' => 836,  'nombre' => 'GUAYANA FRANCESA'],
            ['id_pais' => 837,  'nombre' => 'GUERNSEY'],
            ['id_pais' => 838,  'nombre' => 'GUINEA ECUATORIAL'],
            ['id_pais' => 839,  'nombre' => 'GUINEA-BISSAU'],
            ['id_pais' => 840,  'nombre' => 'HAITÍ'],
            ['id_pais' => 841,  'nombre' => 'HONG KONG'],
            ['id_pais' => 842,  'nombre' => 'HUNGRÍA'],
            ['id_pais' => 843,  'nombre' => 'INDONESIA'],
            ['id_pais' => 844,  'nombre' => 'IRAK'],
            ['id_pais' => 845,  'nombre' => 'REPÚBLICA ISLÁMICA DE IRÁN'],
            ['id_pais' => 846,  'nombre' => 'ISLA DE MAN'],
            ['id_pais' => 847,  'nombre' => 'ISLA NAVIDAD'],
            ['id_pais' => 848,  'nombre' => 'ISLA COCOS'],
            ['id_pais' => 849,  'nombre' => 'ISLANDIA'],
            ['id_pais' => 850,  'nombre' => 'SALOMÓN, ISLAS'],
            ['id_pais' => 851,  'nombre' => 'ISLAS COOK'],
            ['id_pais' => 852,  'nombre' => 'ISRAEL'],
            ['id_pais' => 853,  'nombre' => 'ISLAS FAROE'],
            ['id_pais' => 854,  'nombre' => 'ISLAS AZORES'],
            ['id_pais' => 855,  'nombre' => 'ISLA QESHM'],
            ['id_pais' => 856,  'nombre' => 'ISLAS MALVINAS (FALKLAND)'],
            ['id_pais' => 857,  'nombre' => 'JAMAICA'],
            ['id_pais' => 858,  'nombre' => 'ISLAS MARIANAS DEL NORTE'],
            ['id_pais' => 859,  'nombre' => 'ISLAS MARSHALL'],
            ['id_pais' => 860,  'nombre' => 'ISLAS PITCAIM'],
            ['id_pais' => 861,  'nombre' => 'ISLAS TURCAS Y CAICOS'],
            ['id_pais' => 862,  'nombre' => 'JORDANIA'],
            ['id_pais' => 863,  'nombre' => 'KASAKISTÁN'],
            ['id_pais' => 864,  'nombre' => 'ISLAS ULTRAMARINAS DE E.E.U.U'],
            ['id_pais' => 865,  'nombre' => 'KENIA'],
            ['id_pais' => 866,  'nombre' => 'KIRIBATI'],
            ['id_pais' => 867,  'nombre' => 'ISLAS VÍRGENES'],
            ['id_pais' => 868,  'nombre' => 'KUWAIT'],
            ['id_pais' => 869,  'nombre' => 'JERSEY'],
            ['id_pais' => 870,  'nombre' => 'KIRGUISTÁN'],
            ['id_pais' => 871,  'nombre' => 'LAOS, REPÚBLICA DEMOCRÁTICA'],
            ['id_pais' => 872,  'nombre' => 'LETONIA'],
            ['id_pais' => 873,  'nombre' => 'LESOTHO'],
            ['id_pais' => 874,  'nombre' => 'LÍBANO'],
            ['id_pais' => 875,  'nombre' => 'LIBERIA'],
            ['id_pais' => 876,  'nombre' => 'LIBIA'],
            ['id_pais' => 877,  'nombre' => 'LIECHTENSTEIN'],
            ['id_pais' => 878,  'nombre' => 'LITUANIA'],
            ['id_pais' => 879,  'nombre' => 'MACAO'],
            ['id_pais' => 880,  'nombre' => 'MADAGASCAR'],
            ['id_pais' => 881,  'nombre' => 'MACEDONIA'],
            ['id_pais' => 882,  'nombre' => 'MALASIA'],
            ['id_pais' => 883,  'nombre' => 'MALÍ'],
            ['id_pais' => 884,  'nombre' => 'MALAWI'],
            ['id_pais' => 885,  'nombre' => 'MALDIVAS'],
            ['id_pais' => 886,  'nombre' => 'MALÍ'],
            ['id_pais' => 887,  'nombre' => 'MALTA'],
            ['id_pais' => 888,  'nombre' => 'MARRUECOS'],
            ['id_pais' => 889,  'nombre' => 'MASCATE Y OMAN'],
            ['id_pais' => 890,  'nombre' => 'MAURICIO'],
            ['id_pais' => 891,  'nombre' => 'MAURITANIA'],
            ['id_pais' => 892,  'nombre' => 'MAYOTTE'],
            ['id_pais' => 893,  'nombre' => 'MICRONESIA'],
            ['id_pais' => 894,  'nombre' => 'REPÚBLICA DE MOLDAVIA'],
            ['id_pais' => 895,  'nombre' => 'MONACO'],
            ['id_pais' => 896,  'nombre' => 'MONGOLIA'],
            ['id_pais' => 897,  'nombre' => 'MONTENEGRO'],
            ['id_pais' => 898,  'nombre' => 'MONTSERRAT'],
            ['id_pais' => 899,  'nombre' => 'MOZAMBIQUE'],
            ['id_pais' => 900,  'nombre' => 'NAMIBIA'],
            ['id_pais' => 901,  'nombre' => 'NAURU'],
            ['id_pais' => 902,  'nombre' => 'NEPAL'],
            ['id_pais' => 903,  'nombre' => 'NÍGER'],
            ['id_pais' => 904,  'nombre' => 'NIGERIA'],
            ['id_pais' => 905,  'nombre' => 'NIUE'],
            ['id_pais' => 906,  'nombre' => 'ISLA NORFOLK'],
            ['id_pais' => 907,  'nombre' => 'NORUEGA'],
            ['id_pais' => 908,  'nombre' => 'NUEVA CALEDONIA'],
            ['id_pais' => 909,  'nombre' => 'NUEVA ZELANDA'],
            ['id_pais' => 910,  'nombre' => 'NUEVAS HEBRIDAS'],
            ['id_pais' => 911,  'nombre' => 'PAPUA NV GUINEA'],
            ['id_pais' => 912,  'nombre' => 'PAKISTÁN'],
            ['id_pais' => 913,  'nombre' => 'PALESTINA'],
            ['id_pais' => 914,  'nombre' => 'PALAOS'],
            ['id_pais' => 915,  'nombre' => 'PARAGUAY'],
            ['id_pais' => 916,  'nombre' => 'POLONIA'],
            ['id_pais' => 917,  'nombre' => 'POLINESIA FRANCESA'],
            ['id_pais' => 918,  'nombre' => 'QATAR'],
            ['id_pais' => 919,  'nombre' => 'REINO UNIDO'],
            ['id_pais' => 920,  'nombre' => 'REPÚBLICA CHECA'],
            ['id_pais' => 921,  'nombre' => 'EGIPTO'],
            ['id_pais' => 922,  'nombre' => 'REUNION'],
            ['id_pais' => 923,  'nombre' => 'RODESIA'],
            ['id_pais' => 924,  'nombre' => 'RUANDA'],
            ['id_pais' => 925,  'nombre' => 'ARMENIA'],
            ['id_pais' => 926,  'nombre' => 'RUMANIA'],
            ['id_pais' => 927,  'nombre' => 'SAHARA OCCIDENTAL'],
            ['id_pais' => 928,  'nombre' => 'SAN MARINO'],
            ['id_pais' => 929,  'nombre' => 'SAMOA'],
            ['id_pais' => 930,  'nombre' => 'SAN CRISTÓBAL Y NIEVES'],
            ['id_pais' => 931,  'nombre' => 'SANTA LUCIA'],
            ['id_pais' => 932,  'nombre' => 'SENEGAL'],
            ['id_pais' => 933,  'nombre' => 'SANTO TOMÉ Y PRÍNCIPE'],
            ['id_pais' => 934,  'nombre' => 'SAN VICENTE Y LAS GRANADINAS'],
            ['id_pais' => 935,  'nombre' => 'SIERRA LEONA'],
            ['id_pais' => 936,  'nombre' => 'SAMOA AMERICANA'],
            ['id_pais' => 937,  'nombre' => 'SAN PEDRO Y MIQUELON'],
            ['id_pais' => 938,  'nombre' => 'SINGAPUR'],
            ['id_pais' => 939,  'nombre' => 'SANTA ELENA'],
            ['id_pais' => 940,  'nombre' => 'SIRIA'],
            ['id_pais' => 941,  'nombre' => 'SEYCHELLES'],
            ['id_pais' => 942,  'nombre' => 'SVALBARD Y JAN MAYEN'],
            ['id_pais' => 943,  'nombre' => 'SOMALIA'],
            ['id_pais' => 944,  'nombre' => 'SUDÁFRICA'],
            ['id_pais' => 945,  'nombre' => 'SUDÁN'],
            ['id_pais' => 946,  'nombre' => 'SUECIA'],
            ['id_pais' => 947,  'nombre' => 'SURINÁM'],
            ['id_pais' => 948,  'nombre' => 'SRI LANKA'],
            ['id_pais' => 949,  'nombre' => 'SWAZILANDIA'],
            ['id_pais' => 950,  'nombre' => 'TAYIKISTÁN'],
            ['id_pais' => 951,  'nombre' => 'TAILANDIA'],
            ['id_pais' => 952,  'nombre' => 'TERRITORIO BRITANICO DEL OCEANO INDICO'],
            ['id_pais' => 953,  'nombre' => 'TERRITORIOS AUSTRALES FRANCESES'],
            ['id_pais' => 954,  'nombre' => 'REPÚBLICA UNIDA DE TANZANIA'],
            ['id_pais' => 955,  'nombre' => 'TERRITORIOS PALESTINOS'],
            ['id_pais' => 956,  'nombre' => 'TIMOR ORIENTAL'],
            ['id_pais' => 957,  'nombre' => 'TOGO'],
            ['id_pais' => 958,  'nombre' => 'TOKELAU'],
            ['id_pais' => 959,  'nombre' => 'TURKMENISTÁN'],
            ['id_pais' => 960,  'nombre' => 'TRINIDAD TOBAGO'],
            ['id_pais' => 963,  'nombre' => 'TONGA'],
            ['id_pais' => 964,  'nombre' => 'TÚNEZ'],
            ['id_pais' => 965,  'nombre' => 'TRANSKEI'],
            ['id_pais' => 966,  'nombre' => 'TURQUIA'],
            ['id_pais' => 967,  'nombre' => 'TUVALU'],
            ['id_pais' => 968,  'nombre' => 'UGANDA'],
            ['id_pais' => 969,  'nombre' => 'U R S S'],
            ['id_pais' => 970,  'nombre' => 'RUSIA'],
            ['id_pais' => 971,  'nombre' => 'UCRANIA'],
            ['id_pais' => 972,  'nombre' => 'UZBEKISTÁN'],
            ['id_pais' => 973,  'nombre' => 'CIUDAD DEL VATICANO'],
            ['id_pais' => 974,  'nombre' => 'VANUATU'],
            ['id_pais' => 976,  'nombre' => 'VIETNAM NORTE'],
            ['id_pais' => 977,  'nombre' => 'VIETNAM'],
            ['id_pais' => 978,  'nombre' => 'VIETNAM SUR'],
            ['id_pais' => 979,  'nombre' => 'YEMEN'],
            ['id_pais' => 980,  'nombre' => 'YIBUTI'],
            ['id_pais' => 981,  'nombre' => 'WALLIS Y FUTUNA, ISLAS'],
            ['id_pais' => 982,  'nombre' => 'YUGOSLAVIA'],
            ['id_pais' => 983,  'nombre' => 'ZAIRE'],
            ['id_pais' => 984,  'nombre' => 'ZAMBIA'],
            ['id_pais' => 985,  'nombre' => 'ZIMBABUE'],
            ['id_pais' => 986,  'nombre' => 'BAHAMAS'],
            ['id_pais' => 987,  'nombre' => 'BERMUDAS'],
            ['id_pais' => 988,  'nombre' => 'MARTINICA E.A.'],
            ['id_pais' => 989,  'nombre' => 'PAPÚA, NUEVA GUINEA'],
            ['id_pais' => 990,  'nombre' => 'CAIMÁN, ISLAS'],
            ['id_pais' => 991,  'nombre' => 'ISLAS VIRGENES BRITÁNICAS'],
            ['id_pais' => 992,  'nombre' => 'BONAIRE, SINT EUSTATIUS AND SABA'],
            ['id_pais' => 993,  'nombre' => 'TAIWAN, PROVINCIA DE CHINA'],
            ['id_pais' => 994,  'nombre' => 'VENDA'],
            ['id_pais' => 995,  'nombre' => 'ANTÁRTICA'],
            ['id_pais' => 996,  'nombre' => 'ISLA BOUVET'],
            ['id_pais' => 997,  'nombre' => 'ISLAS GEORGIAS D. S.-SANDWICH D.S.'],
            ['id_pais' => 998,  'nombre' => 'ISLAS HEARD Y MCDONALD'],
            ['id_pais' => 1002, 'nombre' => 'SAINT BARTHÉLEMY'],
            ['id_pais' => 1003, 'nombre' => 'SAINT MARTIN (FRENCH PART)'],
        ];

        $rows = array_map(fn($p) => [
            'id_pais'      => $p['id_pais'],
            'nombre'       => $p['nombre'],
            'activo'       => true,
            'usuario_crea' => $usuarioCrea,
            'usuario_mod'  => null,
            'usuario_elim' => null,
            'created_at'   => $now,
            'updated_at'   => $now,
            'deleted_at'   => null,
        ], $paises);

        // Insertar en lotes de 100 para no saturar la query
        foreach (array_chunk($rows, 100) as $chunk) {
            DB::table('tbl_pais')->insertOrIgnore($chunk);
        }
    }
}