<?php

namespace Database\Seeders\fac;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    public function run(): void
    {
        $paises = [
            ['id_pais' => 1,    'codigo_pais' => 'SV',  'nombre_pais' => 'EL SALVADOR',                                   'mh_codigo_pais' => '9300', 'mh_codigo_pais_new' => 'SV'],
            ['id_pais' => 2,    'codigo_pais' => 'USA', 'nombre_pais' => 'ESTADOS UNIDOS',                                'mh_codigo_pais' => '9450', 'mh_codigo_pais_new' => 'US'],
            ['id_pais' => 3,    'codigo_pais' => 'HN',  'nombre_pais' => 'HONDURAS',                                      'mh_codigo_pais' => '9501', 'mh_codigo_pais_new' => 'HN'],
            ['id_pais' => 4,    'codigo_pais' => 'MEX', 'nombre_pais' => 'MÉXICO',                                        'mh_codigo_pais' => '9600', 'mh_codigo_pais_new' => 'MX'],
            ['id_pais' => 5,    'codigo_pais' => 'PUR', 'nombre_pais' => 'PUERTO RICO',                                   'mh_codigo_pais' => '9850', 'mh_codigo_pais_new' => 'PR'],
            ['id_pais' => 7,    'codigo_pais' => 'CR',  'nombre_pais' => 'COSTA RICA',                                    'mh_codigo_pais' => '9411', 'mh_codigo_pais_new' => 'CR'],
            ['id_pais' => 8,    'codigo_pais' => 'PAN', 'nombre_pais' => 'PANAMÁ',                                        'mh_codigo_pais' => '9642', 'mh_codigo_pais_new' => 'PA'],
            ['id_pais' => 9,    'codigo_pais' => 'GUA', 'nombre_pais' => 'GUATEMALA',                                     'mh_codigo_pais' => '9483', 'mh_codigo_pais_new' => 'GT'],
            ['id_pais' => 11,   'codigo_pais' => 'CA',  'nombre_pais' => 'CANADÁ',                                        'mh_codigo_pais' => '9384', 'mh_codigo_pais_new' => 'CA'],
            ['id_pais' => 13,   'codigo_pais' => 'BRA', 'nombre_pais' => 'BRASIL',                                        'mh_codigo_pais' => '9363', 'mh_codigo_pais_new' => 'BR'],
            ['id_pais' => 17,   'codigo_pais' => 'CHI', 'nombre_pais' => 'CHILE',                                         'mh_codigo_pais' => '9423', 'mh_codigo_pais_new' => 'CL'],
            ['id_pais' => 19,   'codigo_pais' => 'JP',  'nombre_pais' => 'JAPÓN',                                         'mh_codigo_pais' => '9537', 'mh_codigo_pais_new' => 'JP'],
            ['id_pais' => 20,   'codigo_pais' => 'ME',  'nombre_pais' => 'MÉXICO',                                        'mh_codigo_pais' => '9600', 'mh_codigo_pais_new' => 'MY'],
            ['id_pais' => 26,   'codigo_pais' => 'VEN', 'nombre_pais' => 'VENEZUELA',                                     'mh_codigo_pais' => '9741', 'mh_codigo_pais_new' => 'VE'],
            ['id_pais' => 27,   'codigo_pais' => 'NIC', 'nombre_pais' => 'NICARAGUA',                                     'mh_codigo_pais' => '9615', 'mh_codigo_pais_new' => 'NI'],
            ['id_pais' => 28,   'codigo_pais' => 'ECU', 'nombre_pais' => 'ECUADOR',                                       'mh_codigo_pais' => '9444', 'mh_codigo_pais_new' => 'EC'],
            ['id_pais' => 29,   'codigo_pais' => 'COL', 'nombre_pais' => 'COLOMBIA',                                      'mh_codigo_pais' => '9393', 'mh_codigo_pais_new' => 'CO'],
            ['id_pais' => 30,   'codigo_pais' => 'LUX', 'nombre_pais' => 'LUXEMBURGO',                                    'mh_codigo_pais' => '9567', 'mh_codigo_pais_new' => 'LU'],
            ['id_pais' => 31,   'codigo_pais' => 'AG',  'nombre_pais' => 'ARGENTINA',                                     'mh_codigo_pais' => '9330', 'mh_codigo_pais_new' => 'AR'],
            ['id_pais' => 32,   'codigo_pais' => 'POR', 'nombre_pais' => 'PORTUGAL',                                      'mh_codigo_pais' => '9654', 'mh_codigo_pais_new' => 'PT'],
            ['id_pais' => 35,   'codigo_pais' => 'HOL', 'nombre_pais' => 'PAÍSES BAJOS',                                  'mh_codigo_pais' => '9498', 'mh_codigo_pais_new' => 'NL'],
            ['id_pais' => 36,   'codigo_pais' => 'SRB', 'nombre_pais' => 'SERBIA',                                        'mh_codigo_pais' => '9689', 'mh_codigo_pais_new' => 'RS'],
            ['id_pais' => 37,   'codigo_pais' => 'SUI', 'nombre_pais' => 'SUIZA',                                         'mh_codigo_pais' => '9705', 'mh_codigo_pais_new' => 'CH'],
            ['id_pais' => 38,   'codigo_pais' => 'ES',  'nombre_pais' => 'ESPAÑA',                                        'mh_codigo_pais' => '9447', 'mh_codigo_pais_new' => 'ES'],
            ['id_pais' => 39,   'codigo_pais' => 'RD',  'nombre_pais' => 'REPUBLICA DOMINICANA',                          'mh_codigo_pais' => '9441', 'mh_codigo_pais_new' => 'DO'],
            ['id_pais' => 40,   'codigo_pais' => 'BL',  'nombre_pais' => 'BELICE',                                        'mh_codigo_pais' => '9349', 'mh_codigo_pais_new' => 'BZ'],
            ['id_pais' => 41,   'codigo_pais' => 'AL',  'nombre_pais' => 'ALEMANIA',                                      'mh_codigo_pais' => '9311', 'mh_codigo_pais_new' => 'DE'],
            ['id_pais' => 42,   'codigo_pais' => 'IT',  'nombre_pais' => 'ITALIA',                                        'mh_codigo_pais' => '9531', 'mh_codigo_pais_new' => 'IT'],
            ['id_pais' => 43,   'codigo_pais' => 'RU',  'nombre_pais' => 'REINO UNIDO',                                   'mh_codigo_pais' => '9663', 'mh_codigo_pais_new' => 'GB'],
            ['id_pais' => 44,   'codigo_pais' => 'ENG', 'nombre_pais' => 'INGLATERRA',                                    'mh_codigo_pais' => null,   'mh_codigo_pais_new' => null],
            ['id_pais' => 45,   'codigo_pais' => 'FRA', 'nombre_pais' => 'FRANCIA',                                       'mh_codigo_pais' => '9465', 'mh_codigo_pais_new' => 'FR'],
            ['id_pais' => 46,   'codigo_pais' => 'BOL', 'nombre_pais' => 'BOLIVIA',                                       'mh_codigo_pais' => '9357', 'mh_codigo_pais_new' => 'BO'],
            ['id_pais' => 47,   'codigo_pais' => 'PER', 'nombre_pais' => 'PERÚ',                                          'mh_codigo_pais' => '9648', 'mh_codigo_pais_new' => 'PE'],
            ['id_pais' => 48,   'codigo_pais' => 'URU', 'nombre_pais' => 'URUGUAY',                                       'mh_codigo_pais' => '9735', 'mh_codigo_pais_new' => 'UY'],
            ['id_pais' => 49,   'codigo_pais' => 'SIG', 'nombre_pais' => 'SINGAPUR',                                      'mh_codigo_pais' => '9687', 'mh_codigo_pais_new' => 'SG'],
            ['id_pais' => 51,   'codigo_pais' => 'TES', 'nombre_pais' => 'FRANCIA',                                       'mh_codigo_pais' => '9465', 'mh_codigo_pais_new' => 'FR'],
            ['id_pais' => 52,   'codigo_pais' => 'IR',  'nombre_pais' => 'IRLANDA',                                       'mh_codigo_pais' => '9522', 'mh_codigo_pais_new' => 'IE'],
            ['id_pais' => 53,   'codigo_pais' => 'CRO', 'nombre_pais' => 'CROACIA',                                       'mh_codigo_pais' => '9641', 'mh_codigo_pais_new' => 'HR'],
            ['id_pais' => 54,   'codigo_pais' => 'IN',  'nombre_pais' => 'INDIA',                                         'mh_codigo_pais' => '9510', 'mh_codigo_pais_new' => 'IN'],
            ['id_pais' => 763,  'codigo_pais' => 'AF',  'nombre_pais' => 'AFGANISTÁN',                                    'mh_codigo_pais' => '9303', 'mh_codigo_pais_new' => 'AF'],
            ['id_pais' => 764,  'codigo_pais' => 'AD',  'nombre_pais' => 'ALAND',                                         'mh_codigo_pais' => '9304', 'mh_codigo_pais_new' => 'AX'],
            ['id_pais' => 765,  'codigo_pais' => 'ALB', 'nombre_pais' => 'ALBANIA',                                       'mh_codigo_pais' => '9306', 'mh_codigo_pais_new' => 'AL'],
            ['id_pais' => 766,  'codigo_pais' => 'ALO', 'nombre_pais' => 'ALEMANIA OCCID',                                'mh_codigo_pais' => '9309', 'mh_codigo_pais_new' => null],
            ['id_pais' => 767,  'codigo_pais' => 'ALR', 'nombre_pais' => 'ALEMANIA ORIENT',                               'mh_codigo_pais' => '9310', 'mh_codigo_pais_new' => null],
            ['id_pais' => 768,  'codigo_pais' => 'ALT', 'nombre_pais' => 'ALTO VOLTA',                                    'mh_codigo_pais' => '9315', 'mh_codigo_pais_new' => null],
            ['id_pais' => 769,  'codigo_pais' => 'AND', 'nombre_pais' => 'ANDORRA',                                       'mh_codigo_pais' => '9317', 'mh_codigo_pais_new' => 'AD'],
            ['id_pais' => 770,  'codigo_pais' => 'ANG', 'nombre_pais' => 'ANGOLA',                                        'mh_codigo_pais' => '9318', 'mh_codigo_pais_new' => 'AO'],
            ['id_pais' => 771,  'codigo_pais' => 'ANT', 'nombre_pais' => 'ANTIG Y BARBUDA',                               'mh_codigo_pais' => '9319', 'mh_codigo_pais_new' => 'AG'],
            ['id_pais' => 772,  'codigo_pais' => 'ALA', 'nombre_pais' => 'ANGUILA',                                       'mh_codigo_pais' => '9320', 'mh_codigo_pais_new' => 'AI'],
            ['id_pais' => 773,  'codigo_pais' => 'ARA', 'nombre_pais' => 'ARABIA SAUDITA',                                'mh_codigo_pais' => '9324', 'mh_codigo_pais_new' => 'SA'],
            ['id_pais' => 774,  'codigo_pais' => 'ARG', 'nombre_pais' => 'ARGELIA',                                       'mh_codigo_pais' => '9327', 'mh_codigo_pais_new' => 'DZ'],
            ['id_pais' => 775,  'codigo_pais' => 'ARU', 'nombre_pais' => 'ARUBA',                                         'mh_codigo_pais' => '9332', 'mh_codigo_pais_new' => 'AW'],
            ['id_pais' => 776,  'codigo_pais' => 'ATR', 'nombre_pais' => 'AUSTRALIA',                                     'mh_codigo_pais' => '9333', 'mh_codigo_pais_new' => 'AU'],
            ['id_pais' => 777,  'codigo_pais' => 'AUS', 'nombre_pais' => 'AUSTRIA',                                       'mh_codigo_pais' => '9336', 'mh_codigo_pais_new' => 'AT'],
            ['id_pais' => 778,  'codigo_pais' => 'AZE', 'nombre_pais' => 'AZERBAIYÁN',                                    'mh_codigo_pais' => '9338', 'mh_codigo_pais_new' => 'AZ'],
            ['id_pais' => 779,  'codigo_pais' => 'BAN', 'nombre_pais' => 'BANGLADESH',                                    'mh_codigo_pais' => '9339', 'mh_codigo_pais_new' => 'BD'],
            ['id_pais' => 780,  'codigo_pais' => 'BHR', 'nombre_pais' => 'BAHREIN',                                       'mh_codigo_pais' => '9342', 'mh_codigo_pais_new' => 'BH'],
            ['id_pais' => 781,  'codigo_pais' => 'BAR', 'nombre_pais' => 'BARBADOS',                                      'mh_codigo_pais' => '9345', 'mh_codigo_pais_new' => 'BB'],
            ['id_pais' => 782,  'codigo_pais' => 'BEL', 'nombre_pais' => 'BÉLGICA',                                       'mh_codigo_pais' => '9348', 'mh_codigo_pais_new' => 'BE'],
            ['id_pais' => 783,  'codigo_pais' => 'BEI', 'nombre_pais' => 'BELICE',                                        'mh_codigo_pais' => '9349', 'mh_codigo_pais_new' => 'BZ'],
            ['id_pais' => 784,  'codigo_pais' => 'BEN', 'nombre_pais' => 'BENIN',                                         'mh_codigo_pais' => '9350', 'mh_codigo_pais_new' => 'BJ'],
            ['id_pais' => 785,  'codigo_pais' => 'BIE', 'nombre_pais' => 'BIELORRUSIA',                                   'mh_codigo_pais' => '9353', 'mh_codigo_pais_new' => 'BY'],
            ['id_pais' => 786,  'codigo_pais' => 'BIR', 'nombre_pais' => 'MYANMAR',                                       'mh_codigo_pais' => '9354', 'mh_codigo_pais_new' => 'MM'],
            ['id_pais' => 787,  'codigo_pais' => 'BOS', 'nombre_pais' => 'BOSNIA Y HERZEGOVINA',                          'mh_codigo_pais' => '9359', 'mh_codigo_pais_new' => 'BA'],
            ['id_pais' => 788,  'codigo_pais' => 'BOT', 'nombre_pais' => 'BOTSWANA',                                      'mh_codigo_pais' => '9360', 'mh_codigo_pais_new' => 'BW'],
            ['id_pais' => 789,  'codigo_pais' => 'BRU', 'nombre_pais' => 'BRUNEI',                                        'mh_codigo_pais' => '9366', 'mh_codigo_pais_new' => 'BN'],
            ['id_pais' => 790,  'codigo_pais' => 'BUL', 'nombre_pais' => 'BULGARIA',                                      'mh_codigo_pais' => '9369', 'mh_codigo_pais_new' => 'BG'],
            ['id_pais' => 791,  'codigo_pais' => 'BUK', 'nombre_pais' => 'BURKINA FASO',                                  'mh_codigo_pais' => '9371', 'mh_codigo_pais_new' => 'BF'],
            ['id_pais' => 792,  'codigo_pais' => 'BUR', 'nombre_pais' => 'BURUNDI',                                       'mh_codigo_pais' => '9372', 'mh_codigo_pais_new' => 'BI'],
            ['id_pais' => 793,  'codigo_pais' => 'BOP', 'nombre_pais' => 'BOPHUTHATSWANA',                                'mh_codigo_pais' => '9374', 'mh_codigo_pais_new' => null],
            ['id_pais' => 794,  'codigo_pais' => 'BUT', 'nombre_pais' => 'BUTÁN',                                         'mh_codigo_pais' => '9375', 'mh_codigo_pais_new' => 'BT'],
            ['id_pais' => 795,  'codigo_pais' => 'CAB', 'nombre_pais' => 'CABO VERDE',                                    'mh_codigo_pais' => '9377', 'mh_codigo_pais_new' => 'CV'],
            ['id_pais' => 796,  'codigo_pais' => 'CMB', 'nombre_pais' => 'CAMBOYA',                                       'mh_codigo_pais' => '9378', 'mh_codigo_pais_new' => 'KH'],
            ['id_pais' => 797,  'codigo_pais' => 'CAM', 'nombre_pais' => 'CAMERÚN',                                       'mh_codigo_pais' => '9381', 'mh_codigo_pais_new' => 'CM'],
            ['id_pais' => 798,  'codigo_pais' => 'CEI', 'nombre_pais' => 'CEILAN',                                        'mh_codigo_pais' => '9387', 'mh_codigo_pais_new' => null],
            ['id_pais' => 799,  'codigo_pais' => 'CTR', 'nombre_pais' => 'CENTROAFRICANA, REPÚBLICA',                     'mh_codigo_pais' => '9390', 'mh_codigo_pais_new' => 'CF'],
            ['id_pais' => 800,  'codigo_pais' => 'COM', 'nombre_pais' => 'COMORAS',                                       'mh_codigo_pais' => '9394', 'mh_codigo_pais_new' => 'KM'],
            ['id_pais' => 801,  'codigo_pais' => 'RPC', 'nombre_pais' => 'CONGO',                                         'mh_codigo_pais' => '9396', 'mh_codigo_pais_new' => 'CG'],
            ['id_pais' => 802,  'codigo_pais' => 'RDC', 'nombre_pais' => 'REP. DEMOCRÁTICA POPULAR DEL CONGO',            'mh_codigo_pais' => '9399', 'mh_codigo_pais_new' => 'CD'],
            ['id_pais' => 803,  'codigo_pais' => 'CN',  'nombre_pais' => 'REP. DEMOCRÁTICA POPULAR DE COREA DEL NORTE',   'mh_codigo_pais' => '9402', 'mh_codigo_pais_new' => 'KP'],
            ['id_pais' => 804,  'codigo_pais' => 'CS',  'nombre_pais' => 'REPÚBLICA DE COREA',                            'mh_codigo_pais' => '9405', 'mh_codigo_pais_new' => 'KR'],
            ['id_pais' => 805,  'codigo_pais' => 'COS', 'nombre_pais' => 'COSTA DE MARFIL',                               'mh_codigo_pais' => '9408', 'mh_codigo_pais_new' => 'CI'],
            ['id_pais' => 806,  'codigo_pais' => 'CUB', 'nombre_pais' => 'CUBA',                                          'mh_codigo_pais' => '9414', 'mh_codigo_pais_new' => 'CU'],
            ['id_pais' => 807,  'codigo_pais' => 'CHA', 'nombre_pais' => 'CHAD',                                          'mh_codigo_pais' => '9417', 'mh_codigo_pais_new' => 'TD'],
            ['id_pais' => 808,  'codigo_pais' => 'CHE', 'nombre_pais' => 'CHECOSLOVAQUIA',                                'mh_codigo_pais' => '9420', 'mh_codigo_pais_new' => null],
            ['id_pais' => 809,  'codigo_pais' => 'PRH', 'nombre_pais' => 'CHINA',                                         'mh_codigo_pais' => '9426', 'mh_codigo_pais_new' => 'CN'],
            ['id_pais' => 810,  'codigo_pais' => 'CHP', 'nombre_pais' => 'CHIPRE',                                        'mh_codigo_pais' => '9432', 'mh_codigo_pais_new' => 'CY'],
            ['id_pais' => 811,  'codigo_pais' => 'DAH', 'nombre_pais' => 'DAHOMEY',                                       'mh_codigo_pais' => '9435', 'mh_codigo_pais_new' => null],
            ['id_pais' => 812,  'codigo_pais' => 'DIN', 'nombre_pais' => 'DINAMARCA',                                     'mh_codigo_pais' => '9438', 'mh_codigo_pais_new' => 'DK'],
            ['id_pais' => 813,  'codigo_pais' => 'DJI', 'nombre_pais' => 'DJIBOUTÍ',                                      'mh_codigo_pais' => '9439', 'mh_codigo_pais_new' => 'DJ'],
            ['id_pais' => 814,  'codigo_pais' => 'DOM', 'nombre_pais' => 'DOMINICA',                                      'mh_codigo_pais' => '9440', 'mh_codigo_pais_new' => 'DM'],
            ['id_pais' => 815,  'codigo_pais' => 'EMI', 'nombre_pais' => 'EMIRATOS ÁRABES UNIDOS',                        'mh_codigo_pais' => '9446', 'mh_codigo_pais_new' => 'AE'],
            ['id_pais' => 816,  'codigo_pais' => 'SLV', 'nombre_pais' => 'ESLOVAQUIA',                                    'mh_codigo_pais' => '9449', 'mh_codigo_pais_new' => 'SK'],
            ['id_pais' => 817,  'codigo_pais' => 'ESL', 'nombre_pais' => 'ESLOVENIA',                                     'mh_codigo_pais' => '9451', 'mh_codigo_pais_new' => 'SI'],
            ['id_pais' => 818,  'codigo_pais' => 'ETI', 'nombre_pais' => 'ETIOPÍA',                                       'mh_codigo_pais' => '9453', 'mh_codigo_pais_new' => 'ET'],
            ['id_pais' => 819,  'codigo_pais' => 'ERI', 'nombre_pais' => 'ERITREA',                                       'mh_codigo_pais' => '9454', 'mh_codigo_pais_new' => 'ER'],
            ['id_pais' => 820,  'codigo_pais' => 'FIJ', 'nombre_pais' => 'FIJI',                                          'mh_codigo_pais' => '9456', 'mh_codigo_pais_new' => 'FJ'],
            ['id_pais' => 821,  'codigo_pais' => 'EST', 'nombre_pais' => 'ESTONIA',                                       'mh_codigo_pais' => '9457', 'mh_codigo_pais_new' => 'EE'],
            ['id_pais' => 822,  'codigo_pais' => 'FIL', 'nombre_pais' => 'FILIPINAS',                                     'mh_codigo_pais' => '9459', 'mh_codigo_pais_new' => 'PH'],
            ['id_pais' => 823,  'codigo_pais' => 'FIN', 'nombre_pais' => 'FINLANDIA',                                     'mh_codigo_pais' => '9462', 'mh_codigo_pais_new' => 'FI'],
            ['id_pais' => 824,  'codigo_pais' => 'GAB', 'nombre_pais' => 'GABÓN',                                         'mh_codigo_pais' => '9468', 'mh_codigo_pais_new' => 'GA'],
            ['id_pais' => 825,  'codigo_pais' => 'GAM', 'nombre_pais' => 'GAMBIA',                                        'mh_codigo_pais' => '9471', 'mh_codigo_pais_new' => 'GM'],
            ['id_pais' => 826,  'codigo_pais' => 'GEO', 'nombre_pais' => 'GEORGIA',                                       'mh_codigo_pais' => '9472', 'mh_codigo_pais_new' => 'GE'],
            ['id_pais' => 827,  'codigo_pais' => 'GHA', 'nombre_pais' => 'GHANA',                                         'mh_codigo_pais' => '9474', 'mh_codigo_pais_new' => 'GH'],
            ['id_pais' => 828,  'codigo_pais' => 'GIB', 'nombre_pais' => 'GIBRALTAR',                                     'mh_codigo_pais' => '9477', 'mh_codigo_pais_new' => 'GI'],
            ['id_pais' => 829,  'codigo_pais' => 'GRE', 'nombre_pais' => 'GRECIA',                                        'mh_codigo_pais' => '9480', 'mh_codigo_pais_new' => 'GR'],
            ['id_pais' => 830,  'codigo_pais' => 'GRN', 'nombre_pais' => 'GRANADA',                                       'mh_codigo_pais' => '9481', 'mh_codigo_pais_new' => 'GD'],
            ['id_pais' => 831,  'codigo_pais' => 'GRO', 'nombre_pais' => 'GROENLANDIA',                                   'mh_codigo_pais' => '9482', 'mh_codigo_pais_new' => 'GL'],
            ['id_pais' => 832,  'codigo_pais' => 'GUI', 'nombre_pais' => 'GUINEA',                                        'mh_codigo_pais' => '9486', 'mh_codigo_pais_new' => 'GN'],
            ['id_pais' => 833,  'codigo_pais' => 'GUY', 'nombre_pais' => 'GUYANA',                                        'mh_codigo_pais' => '9487', 'mh_codigo_pais_new' => 'GY'],
            ['id_pais' => 834,  'codigo_pais' => 'GDP', 'nombre_pais' => 'GUADALUPE',                                     'mh_codigo_pais' => '9489', 'mh_codigo_pais_new' => 'GP'],
            ['id_pais' => 835,  'codigo_pais' => 'GM',  'nombre_pais' => 'GUAM',                                          'mh_codigo_pais' => '9490', 'mh_codigo_pais_new' => 'GU'],
            ['id_pais' => 836,  'codigo_pais' => 'GYF', 'nombre_pais' => 'GUAYANA FRANCESA',                              'mh_codigo_pais' => '9491', 'mh_codigo_pais_new' => 'GF'],
            ['id_pais' => 837,  'codigo_pais' => 'GUE', 'nombre_pais' => 'GUERNSEY',                                      'mh_codigo_pais' => '9492', 'mh_codigo_pais_new' => 'GG'],
            ['id_pais' => 838,  'codigo_pais' => 'GEC', 'nombre_pais' => 'GUINEA ECUATORIAL',                             'mh_codigo_pais' => '9493', 'mh_codigo_pais_new' => 'GQ'],
            ['id_pais' => 839,  'codigo_pais' => 'BB',  'nombre_pais' => 'GUINEA-BISSAU',                                 'mh_codigo_pais' => '9494', 'mh_codigo_pais_new' => 'GW'],
            ['id_pais' => 840,  'codigo_pais' => 'HAI', 'nombre_pais' => 'HAITÍ',                                         'mh_codigo_pais' => '9495', 'mh_codigo_pais_new' => 'HT'],
            ['id_pais' => 841,  'codigo_pais' => 'HON', 'nombre_pais' => 'HONG KONG',                                     'mh_codigo_pais' => '9504', 'mh_codigo_pais_new' => 'HK'],
            ['id_pais' => 842,  'codigo_pais' => 'HUN', 'nombre_pais' => 'HUNGRÍA',                                       'mh_codigo_pais' => '9507', 'mh_codigo_pais_new' => 'HU'],
            ['id_pais' => 843,  'codigo_pais' => 'IND', 'nombre_pais' => 'INDONESIA',                                     'mh_codigo_pais' => '9513', 'mh_codigo_pais_new' => 'ID'],
            ['id_pais' => 844,  'codigo_pais' => 'IRA', 'nombre_pais' => 'IRAK',                                          'mh_codigo_pais' => '9516', 'mh_codigo_pais_new' => 'IQ'],
            ['id_pais' => 845,  'codigo_pais' => 'IRN', 'nombre_pais' => 'REPÚBLICA ISLÁMICA DE IRÁN',                    'mh_codigo_pais' => '9519', 'mh_codigo_pais_new' => 'IR'],
            ['id_pais' => 846,  'codigo_pais' => 'ISM', 'nombre_pais' => 'ISLA DE MAN',                                   'mh_codigo_pais' => '9521', 'mh_codigo_pais_new' => 'IM'],
            ['id_pais' => 847,  'codigo_pais' => 'ISN', 'nombre_pais' => 'ISLA NAVIDAD',                                  'mh_codigo_pais' => '9523', 'mh_codigo_pais_new' => 'CX'],
            ['id_pais' => 848,  'codigo_pais' => 'ISC', 'nombre_pais' => 'ISLA COCOS',                                    'mh_codigo_pais' => '9524', 'mh_codigo_pais_new' => 'CC'],
            ['id_pais' => 849,  'codigo_pais' => 'ISL', 'nombre_pais' => 'ISLANDIA',                                      'mh_codigo_pais' => '9525', 'mh_codigo_pais_new' => 'IS'],
            ['id_pais' => 850,  'codigo_pais' => 'ISS', 'nombre_pais' => 'SALOMÓN, ISLAS',                                'mh_codigo_pais' => '9526', 'mh_codigo_pais_new' => 'SB'],
            ['id_pais' => 851,  'codigo_pais' => 'ISK', 'nombre_pais' => 'ISLAS COOK',                                    'mh_codigo_pais' => '9527', 'mh_codigo_pais_new' => 'CK'],
            ['id_pais' => 852,  'codigo_pais' => 'ISR', 'nombre_pais' => 'ISRAEL',                                        'mh_codigo_pais' => '9528', 'mh_codigo_pais_new' => 'IL'],
            ['id_pais' => 853,  'codigo_pais' => 'ISF', 'nombre_pais' => 'ISLAS FAROE',                                   'mh_codigo_pais' => '9529', 'mh_codigo_pais_new' => 'FO'],
            ['id_pais' => 854,  'codigo_pais' => 'ISA', 'nombre_pais' => 'ISLAS AZORES',                                  'mh_codigo_pais' => '9530', 'mh_codigo_pais_new' => null],
            ['id_pais' => 855,  'codigo_pais' => 'ISQ', 'nombre_pais' => 'ISLA QESHM',                                    'mh_codigo_pais' => '9532', 'mh_codigo_pais_new' => null],
            ['id_pais' => 856,  'codigo_pais' => 'IV',  'nombre_pais' => 'ISLAS MALVINAS (FALKLAND)',                      'mh_codigo_pais' => '9533', 'mh_codigo_pais_new' => 'FK'],
            ['id_pais' => 857,  'codigo_pais' => 'JAM', 'nombre_pais' => 'JAMAICA',                                       'mh_codigo_pais' => '9534', 'mh_codigo_pais_new' => 'JM'],
            ['id_pais' => 858,  'codigo_pais' => 'IMN', 'nombre_pais' => 'ISLAS MARIANAS DEL NORTE',                      'mh_codigo_pais' => '9535', 'mh_codigo_pais_new' => 'MP'],
            ['id_pais' => 859,  'codigo_pais' => 'IMS', 'nombre_pais' => 'ISLAS MARSHALL',                                'mh_codigo_pais' => '9536', 'mh_codigo_pais_new' => 'MH'],
            ['id_pais' => 860,  'codigo_pais' => 'IPC', 'nombre_pais' => 'ISLAS PITCAIM',                                 'mh_codigo_pais' => '9538', 'mh_codigo_pais_new' => 'PN'],
            ['id_pais' => 861,  'codigo_pais' => 'ITC', 'nombre_pais' => 'ISLAS TURCAS Y CAICOS',                         'mh_codigo_pais' => '9539', 'mh_codigo_pais_new' => 'TC'],
            ['id_pais' => 862,  'codigo_pais' => 'JOR', 'nombre_pais' => 'JORDANIA',                                      'mh_codigo_pais' => '9540', 'mh_codigo_pais_new' => 'JO'],
            ['id_pais' => 863,  'codigo_pais' => 'KKK', 'nombre_pais' => 'KASAKISTÁN',                                    'mh_codigo_pais' => '9541', 'mh_codigo_pais_new' => 'KZ'],
            ['id_pais' => 864,  'codigo_pais' => 'IUS', 'nombre_pais' => 'ISLAS ULTRAMARINAS DE E.E.U.U',                 'mh_codigo_pais' => '9542', 'mh_codigo_pais_new' => 'UM'],
            ['id_pais' => 865,  'codigo_pais' => 'KEN', 'nombre_pais' => 'KENIA',                                         'mh_codigo_pais' => '9543', 'mh_codigo_pais_new' => 'KE'],
            ['id_pais' => 866,  'codigo_pais' => 'KBT', 'nombre_pais' => 'KIRIBATI',                                      'mh_codigo_pais' => '9544', 'mh_codigo_pais_new' => 'KI'],
            ['id_pais' => 867,  'codigo_pais' => 'IVE', 'nombre_pais' => 'ISLAS VÍRGENES',                                'mh_codigo_pais' => '9545', 'mh_codigo_pais_new' => 'VI'],
            ['id_pais' => 868,  'codigo_pais' => 'KUW', 'nombre_pais' => 'KUWAIT',                                        'mh_codigo_pais' => '9546', 'mh_codigo_pais_new' => 'KW'],
            ['id_pais' => 869,  'codigo_pais' => 'JER', 'nombre_pais' => 'JERSEY',                                        'mh_codigo_pais' => '9547', 'mh_codigo_pais_new' => 'JE'],
            ['id_pais' => 870,  'codigo_pais' => 'KIR', 'nombre_pais' => 'KIRGUISTÁN',                                    'mh_codigo_pais' => '9548', 'mh_codigo_pais_new' => 'KG'],
            ['id_pais' => 871,  'codigo_pais' => 'LAO', 'nombre_pais' => 'LAOS, REPÚBLICA DEMOCRÁTICA',                   'mh_codigo_pais' => '9549', 'mh_codigo_pais_new' => 'LA'],
            ['id_pais' => 872,  'codigo_pais' => 'LET', 'nombre_pais' => 'LETONIA',                                       'mh_codigo_pais' => '9551', 'mh_codigo_pais_new' => 'LV'],
            ['id_pais' => 873,  'codigo_pais' => 'LES', 'nombre_pais' => 'LESOTHO',                                       'mh_codigo_pais' => '9552', 'mh_codigo_pais_new' => 'LS'],
            ['id_pais' => 874,  'codigo_pais' => 'LBN', 'nombre_pais' => 'LÍBANO',                                        'mh_codigo_pais' => '9555', 'mh_codigo_pais_new' => 'LB'],
            ['id_pais' => 875,  'codigo_pais' => 'LBR', 'nombre_pais' => 'LIBERIA',                                       'mh_codigo_pais' => '9558', 'mh_codigo_pais_new' => 'LR'],
            ['id_pais' => 876,  'codigo_pais' => 'LIB', 'nombre_pais' => 'LIBIA',                                         'mh_codigo_pais' => '9561', 'mh_codigo_pais_new' => 'LY'],
            ['id_pais' => 877,  'codigo_pais' => 'LIE', 'nombre_pais' => 'LIECHTENSTEIN',                                 'mh_codigo_pais' => '9564', 'mh_codigo_pais_new' => 'LI'],
            ['id_pais' => 878,  'codigo_pais' => 'LIT', 'nombre_pais' => 'LITUANIA',                                      'mh_codigo_pais' => '9565', 'mh_codigo_pais_new' => 'LT'],
            ['id_pais' => 879,  'codigo_pais' => 'MAC', 'nombre_pais' => 'MACAO',                                         'mh_codigo_pais' => '9568', 'mh_codigo_pais_new' => 'MO'],
            ['id_pais' => 880,  'codigo_pais' => 'MAD', 'nombre_pais' => 'MADAGASCAR',                                    'mh_codigo_pais' => '9570', 'mh_codigo_pais_new' => 'MG'],
            ['id_pais' => 881,  'codigo_pais' => 'MCD', 'nombre_pais' => 'MACEDONIA',                                     'mh_codigo_pais' => '9571', 'mh_codigo_pais_new' => 'MK'],
            ['id_pais' => 882,  'codigo_pais' => 'MAL', 'nombre_pais' => 'MALASIA',                                       'mh_codigo_pais' => '9573', 'mh_codigo_pais_new' => 'MY'],
            ['id_pais' => 883,  'codigo_pais' => 'MAI', 'nombre_pais' => 'MALÍ',                                          'mh_codigo_pais' => '9574', 'mh_codigo_pais_new' => 'ML'],
            ['id_pais' => 884,  'codigo_pais' => 'MLW', 'nombre_pais' => 'MALAWI',                                        'mh_codigo_pais' => '9576', 'mh_codigo_pais_new' => 'MW'],
            ['id_pais' => 885,  'codigo_pais' => 'MDV', 'nombre_pais' => 'MALDIVAS',                                      'mh_codigo_pais' => '9577', 'mh_codigo_pais_new' => 'MV'],
            ['id_pais' => 886,  'codigo_pais' => 'ML',  'nombre_pais' => 'MALÍ',                                          'mh_codigo_pais' => '9579', 'mh_codigo_pais_new' => 'ML'],
            ['id_pais' => 887,  'codigo_pais' => 'MLT', 'nombre_pais' => 'MALTA',                                         'mh_codigo_pais' => '9582', 'mh_codigo_pais_new' => 'MT'],
            ['id_pais' => 888,  'codigo_pais' => 'MAR', 'nombre_pais' => 'MARRUECOS',                                     'mh_codigo_pais' => '9585', 'mh_codigo_pais_new' => 'MA'],
            ['id_pais' => 889,  'codigo_pais' => 'MAS', 'nombre_pais' => 'MASCATE Y OMAN',                                'mh_codigo_pais' => '9591', 'mh_codigo_pais_new' => null],
            ['id_pais' => 890,  'codigo_pais' => 'MAU', 'nombre_pais' => 'MAURICIO',                                      'mh_codigo_pais' => '9594', 'mh_codigo_pais_new' => 'MU'],
            ['id_pais' => 891,  'codigo_pais' => 'MRT', 'nombre_pais' => 'MAURITANIA',                                    'mh_codigo_pais' => '9597', 'mh_codigo_pais_new' => 'MR'],
            ['id_pais' => 892,  'codigo_pais' => 'MAY', 'nombre_pais' => 'MAYOTTE',                                       'mh_codigo_pais' => '9598', 'mh_codigo_pais_new' => 'YT'],
            ['id_pais' => 893,  'codigo_pais' => 'MIC', 'nombre_pais' => 'MICRONESIA',                                    'mh_codigo_pais' => '9601', 'mh_codigo_pais_new' => 'FM'],
            ['id_pais' => 894,  'codigo_pais' => 'MOL', 'nombre_pais' => 'REPÚBLICA DE MOLDAVIA',                         'mh_codigo_pais' => '9602', 'mh_codigo_pais_new' => 'MD'],
            ['id_pais' => 895,  'codigo_pais' => 'MNC', 'nombre_pais' => 'MONACO',                                        'mh_codigo_pais' => '9603', 'mh_codigo_pais_new' => 'MC'],
            ['id_pais' => 896,  'codigo_pais' => 'MNG', 'nombre_pais' => 'MONGOLIA',                                      'mh_codigo_pais' => '9606', 'mh_codigo_pais_new' => 'MN'],
            ['id_pais' => 897,  'codigo_pais' => 'MNT', 'nombre_pais' => 'MONTENEGRO',                                    'mh_codigo_pais' => '9607', 'mh_codigo_pais_new' => 'ME'],
            ['id_pais' => 898,  'codigo_pais' => 'MNS', 'nombre_pais' => 'MONTSERRAT',                                    'mh_codigo_pais' => '9608', 'mh_codigo_pais_new' => 'MS'],
            ['id_pais' => 899,  'codigo_pais' => 'MOZ', 'nombre_pais' => 'MOZAMBIQUE',                                    'mh_codigo_pais' => '9609', 'mh_codigo_pais_new' => 'MZ'],
            ['id_pais' => 900,  'codigo_pais' => 'NAM', 'nombre_pais' => 'NAMIBIA',                                       'mh_codigo_pais' => '9610', 'mh_codigo_pais_new' => 'NA'],
            ['id_pais' => 901,  'codigo_pais' => 'NAU', 'nombre_pais' => 'NAURU',                                         'mh_codigo_pais' => '9611', 'mh_codigo_pais_new' => 'NR'],
            ['id_pais' => 902,  'codigo_pais' => 'NEP', 'nombre_pais' => 'NEPAL',                                         'mh_codigo_pais' => '9612', 'mh_codigo_pais_new' => 'NP'],
            ['id_pais' => 903,  'codigo_pais' => 'NGR', 'nombre_pais' => 'NÍGER',                                         'mh_codigo_pais' => '9618', 'mh_codigo_pais_new' => 'NE'],
            ['id_pais' => 904,  'codigo_pais' => 'NIG', 'nombre_pais' => 'NIGERIA',                                       'mh_codigo_pais' => '9621', 'mh_codigo_pais_new' => 'NG'],
            ['id_pais' => 905,  'codigo_pais' => 'NIU', 'nombre_pais' => 'NIUE',                                          'mh_codigo_pais' => '9622', 'mh_codigo_pais_new' => 'NU'],
            ['id_pais' => 906,  'codigo_pais' => 'NOR', 'nombre_pais' => 'ISLA NORFOLK',                                  'mh_codigo_pais' => '9623', 'mh_codigo_pais_new' => 'NF'],
            ['id_pais' => 907,  'codigo_pais' => 'NRG', 'nombre_pais' => 'NORUEGA',                                       'mh_codigo_pais' => '9624', 'mh_codigo_pais_new' => 'NO'],
            ['id_pais' => 908,  'codigo_pais' => 'NVA', 'nombre_pais' => 'NUEVA CALEDONIA',                               'mh_codigo_pais' => '9627', 'mh_codigo_pais_new' => 'NC'],
            ['id_pais' => 909,  'codigo_pais' => 'ZEL', 'nombre_pais' => 'NUEVA ZELANDA',                                 'mh_codigo_pais' => '9633', 'mh_codigo_pais_new' => 'NZ'],
            ['id_pais' => 910,  'codigo_pais' => 'NUE', 'nombre_pais' => 'NUEVAS HEBRIDAS',                               'mh_codigo_pais' => '9636', 'mh_codigo_pais_new' => null],
            ['id_pais' => 911,  'codigo_pais' => 'PAP', 'nombre_pais' => 'PAPUA NV GUINEA',                               'mh_codigo_pais' => '9638', 'mh_codigo_pais_new' => 'PG'],
            ['id_pais' => 912,  'codigo_pais' => 'PAK', 'nombre_pais' => 'PAKISTÁN',                                      'mh_codigo_pais' => '9639', 'mh_codigo_pais_new' => 'PK'],
            ['id_pais' => 913,  'codigo_pais' => 'PAL', 'nombre_pais' => 'PALESTINA',                                     'mh_codigo_pais' => '9640', 'mh_codigo_pais_new' => 'PS'],
            ['id_pais' => 914,  'codigo_pais' => 'PLO', 'nombre_pais' => 'PALAOS',                                        'mh_codigo_pais' => '9643', 'mh_codigo_pais_new' => 'PW'],
            ['id_pais' => 915,  'codigo_pais' => 'PAR', 'nombre_pais' => 'PARAGUAY',                                      'mh_codigo_pais' => '9645', 'mh_codigo_pais_new' => 'PY'],
            ['id_pais' => 916,  'codigo_pais' => 'POL', 'nombre_pais' => 'POLONIA',                                       'mh_codigo_pais' => '9651', 'mh_codigo_pais_new' => 'PL'],
            ['id_pais' => 917,  'codigo_pais' => 'PN',  'nombre_pais' => 'POLINESIA FRANCESA',                            'mh_codigo_pais' => '9652', 'mh_codigo_pais_new' => 'PF'],
            ['id_pais' => 918,  'codigo_pais' => 'QAT', 'nombre_pais' => 'QATAR',                                         'mh_codigo_pais' => '9660', 'mh_codigo_pais_new' => 'QA'],
            ['id_pais' => 919,  'codigo_pais' => 'REI', 'nombre_pais' => 'REINO UNIDO',                                   'mh_codigo_pais' => '9663', 'mh_codigo_pais_new' => 'GB'],
            ['id_pais' => 920,  'codigo_pais' => 'REC', 'nombre_pais' => 'REPÚBLICA CHECA',                               'mh_codigo_pais' => '9664', 'mh_codigo_pais_new' => 'CZ'],
            ['id_pais' => 921,  'codigo_pais' => 'EGI', 'nombre_pais' => 'EGIPTO',                                        'mh_codigo_pais' => '9666', 'mh_codigo_pais_new' => 'EG'],
            ['id_pais' => 922,  'codigo_pais' => 'REU', 'nombre_pais' => 'REUNION',                                       'mh_codigo_pais' => '9667', 'mh_codigo_pais_new' => 'RE'],
            ['id_pais' => 923,  'codigo_pais' => 'ROD', 'nombre_pais' => 'RODESIA',                                       'mh_codigo_pais' => '9669', 'mh_codigo_pais_new' => null],
            ['id_pais' => 924,  'codigo_pais' => 'RUA', 'nombre_pais' => 'RUANDA',                                        'mh_codigo_pais' => '9672', 'mh_codigo_pais_new' => 'RW'],
            ['id_pais' => 925,  'codigo_pais' => 'REP', 'nombre_pais' => 'ARMENIA',                                       'mh_codigo_pais' => '9673', 'mh_codigo_pais_new' => 'AM'],
            ['id_pais' => 926,  'codigo_pais' => 'RUM', 'nombre_pais' => 'RUMANIA',                                       'mh_codigo_pais' => '9675', 'mh_codigo_pais_new' => 'RO'],
            ['id_pais' => 927,  'codigo_pais' => 'SAH', 'nombre_pais' => 'SAHARA OCCIDENTAL',                             'mh_codigo_pais' => '9676', 'mh_codigo_pais_new' => 'EH'],
            ['id_pais' => 928,  'codigo_pais' => 'SM',  'nombre_pais' => 'SAN MARINO',                                    'mh_codigo_pais' => '9677', 'mh_codigo_pais_new' => 'SM'],
            ['id_pais' => 929,  'codigo_pais' => 'SAM', 'nombre_pais' => 'SAMOA',                                         'mh_codigo_pais' => '9678', 'mh_codigo_pais_new' => 'WS'],
            ['id_pais' => 930,  'codigo_pais' => 'SAI', 'nombre_pais' => 'SAN CRISTÓBAL Y NIEVES',                        'mh_codigo_pais' => '9679', 'mh_codigo_pais_new' => 'KN'],
            ['id_pais' => 931,  'codigo_pais' => 'SLU', 'nombre_pais' => 'SANTA LUCIA',                                   'mh_codigo_pais' => '9680', 'mh_codigo_pais_new' => 'LC'],
            ['id_pais' => 932,  'codigo_pais' => 'SEN', 'nombre_pais' => 'SENEGAL',                                       'mh_codigo_pais' => '9681', 'mh_codigo_pais_new' => 'SN'],
            ['id_pais' => 933,  'codigo_pais' => 'SAO', 'nombre_pais' => 'SANTO TOMÉ Y PRÍNCIPE',                         'mh_codigo_pais' => '9682', 'mh_codigo_pais_new' => 'ST'],
            ['id_pais' => 934,  'codigo_pais' => 'SN',  'nombre_pais' => 'SAN VICENTE Y LAS GRANADINAS',                  'mh_codigo_pais' => '9683', 'mh_codigo_pais_new' => 'VC'],
            ['id_pais' => 935,  'codigo_pais' => 'SIE', 'nombre_pais' => 'SIERRA LEONA',                                  'mh_codigo_pais' => '9684', 'mh_codigo_pais_new' => 'SL'],
            ['id_pais' => 936,  'codigo_pais' => 'SMN', 'nombre_pais' => 'SAMOA AMERICANA',                               'mh_codigo_pais' => '9685', 'mh_codigo_pais_new' => 'AS'],
            ['id_pais' => 937,  'codigo_pais' => 'SPY', 'nombre_pais' => 'SAN PEDRO Y MIQUELON',                          'mh_codigo_pais' => '9686', 'mh_codigo_pais_new' => 'PM'],
            ['id_pais' => 938,  'codigo_pais' => 'SIN', 'nombre_pais' => 'SINGAPUR',                                      'mh_codigo_pais' => '9687', 'mh_codigo_pais_new' => 'SG'],
            ['id_pais' => 939,  'codigo_pais' => 'SNE', 'nombre_pais' => 'SANTA ELENA',                                   'mh_codigo_pais' => '9688', 'mh_codigo_pais_new' => 'SH'],
            ['id_pais' => 940,  'codigo_pais' => 'SIR', 'nombre_pais' => 'SIRIA',                                         'mh_codigo_pais' => '9690', 'mh_codigo_pais_new' => 'SY'],
            ['id_pais' => 941,  'codigo_pais' => 'SEY', 'nombre_pais' => 'SEYCHELLES',                                    'mh_codigo_pais' => '9691', 'mh_codigo_pais_new' => 'SC'],
            ['id_pais' => 942,  'codigo_pais' => 'SVA', 'nombre_pais' => 'SVALBARD Y JAN MAYEN',                          'mh_codigo_pais' => '9692', 'mh_codigo_pais_new' => 'SJ'],
            ['id_pais' => 943,  'codigo_pais' => 'SOM', 'nombre_pais' => 'SOMALIA',                                       'mh_codigo_pais' => '9693', 'mh_codigo_pais_new' => 'SO'],
            ['id_pais' => 944,  'codigo_pais' => 'RSD', 'nombre_pais' => 'SUDÁFRICA',                                     'mh_codigo_pais' => '9696', 'mh_codigo_pais_new' => 'ZA'],
            ['id_pais' => 945,  'codigo_pais' => 'SUD', 'nombre_pais' => 'SUDÁN',                                         'mh_codigo_pais' => '9699', 'mh_codigo_pais_new' => 'SD'],
            ['id_pais' => 946,  'codigo_pais' => 'SUE', 'nombre_pais' => 'SUECIA',                                        'mh_codigo_pais' => '9702', 'mh_codigo_pais_new' => 'SE'],
            ['id_pais' => 947,  'codigo_pais' => 'SUR', 'nombre_pais' => 'SURINÁM',                                       'mh_codigo_pais' => '9706', 'mh_codigo_pais_new' => 'SR'],
            ['id_pais' => 948,  'codigo_pais' => 'SRI', 'nombre_pais' => 'SRI LANKA',                                     'mh_codigo_pais' => '9707', 'mh_codigo_pais_new' => 'LK'],
            ['id_pais' => 949,  'codigo_pais' => 'SCN', 'nombre_pais' => 'SWAZILANDIA',                                   'mh_codigo_pais' => '9708', 'mh_codigo_pais_new' => 'SZ'],
            ['id_pais' => 950,  'codigo_pais' => 'TAY', 'nombre_pais' => 'TAYIKISTÁN',                                    'mh_codigo_pais' => '9709', 'mh_codigo_pais_new' => 'TJ'],
            ['id_pais' => 951,  'codigo_pais' => 'TAI', 'nombre_pais' => 'TAILANDIA',                                     'mh_codigo_pais' => '9711', 'mh_codigo_pais_new' => 'TH'],
            ['id_pais' => 952,  'codigo_pais' => 'TBO', 'nombre_pais' => 'TERRITORIO BRITANICO DEL OCEANO INDICO',        'mh_codigo_pais' => '9712', 'mh_codigo_pais_new' => 'IO'],
            ['id_pais' => 953,  'codigo_pais' => 'TER', 'nombre_pais' => 'TERRITORIOS AUSTRALES FRANCESES',               'mh_codigo_pais' => '9713', 'mh_codigo_pais_new' => 'TF'],
            ['id_pais' => 954,  'codigo_pais' => 'TAN', 'nombre_pais' => 'REPÚBLICA UNIDA DE TANZANIA',                   'mh_codigo_pais' => '9714', 'mh_codigo_pais_new' => 'TZ'],
            ['id_pais' => 955,  'codigo_pais' => 'TPS', 'nombre_pais' => 'TERRITORIOS PALESTINOS',                        'mh_codigo_pais' => '9715', 'mh_codigo_pais_new' => null],
            ['id_pais' => 956,  'codigo_pais' => 'TIM', 'nombre_pais' => 'TIMOR ORIENTAL',                                'mh_codigo_pais' => '9716', 'mh_codigo_pais_new' => 'TL'],
            ['id_pais' => 957,  'codigo_pais' => 'TOG', 'nombre_pais' => 'TOGO',                                          'mh_codigo_pais' => '9717', 'mh_codigo_pais_new' => 'TG'],
            ['id_pais' => 958,  'codigo_pais' => 'TOK', 'nombre_pais' => 'TOKELAU',                                       'mh_codigo_pais' => '9718', 'mh_codigo_pais_new' => 'TK'],
            ['id_pais' => 959,  'codigo_pais' => 'TKM', 'nombre_pais' => 'TURKMENISTÁN',                                  'mh_codigo_pais' => '9719', 'mh_codigo_pais_new' => 'TM'],
            ['id_pais' => 960,  'codigo_pais' => 'TRI', 'nombre_pais' => 'TRINIDAD TOBAGO',                               'mh_codigo_pais' => '9720', 'mh_codigo_pais_new' => 'TT'],
            ['id_pais' => 963,  'codigo_pais' => 'TON', 'nombre_pais' => 'TONGA',                                         'mh_codigo_pais' => '9722', 'mh_codigo_pais_new' => 'TO'],
            ['id_pais' => 964,  'codigo_pais' => 'TUN', 'nombre_pais' => 'TÚNEZ',                                         'mh_codigo_pais' => '9723', 'mh_codigo_pais_new' => 'TN'],
            ['id_pais' => 965,  'codigo_pais' => 'TNS', 'nombre_pais' => 'TRANSKEI',                                      'mh_codigo_pais' => '9725', 'mh_codigo_pais_new' => null],
            ['id_pais' => 966,  'codigo_pais' => 'TUR', 'nombre_pais' => 'TURQUIA',                                       'mh_codigo_pais' => '9726', 'mh_codigo_pais_new' => 'TR'],
            ['id_pais' => 967,  'codigo_pais' => 'TUV', 'nombre_pais' => 'TUVALU',                                        'mh_codigo_pais' => '9727', 'mh_codigo_pais_new' => 'TV'],
            ['id_pais' => 968,  'codigo_pais' => 'UGA', 'nombre_pais' => 'UGANDA',                                        'mh_codigo_pais' => '9729', 'mh_codigo_pais_new' => 'UG'],
            ['id_pais' => 969,  'codigo_pais' => 'U R', 'nombre_pais' => 'U R S S',                                       'mh_codigo_pais' => '9732', 'mh_codigo_pais_new' => null],
            ['id_pais' => 970,  'codigo_pais' => 'RUS', 'nombre_pais' => 'RUSIA',                                         'mh_codigo_pais' => '9733', 'mh_codigo_pais_new' => 'RU'],
            ['id_pais' => 971,  'codigo_pais' => 'UCR', 'nombre_pais' => 'UCRANIA',                                       'mh_codigo_pais' => '9736', 'mh_codigo_pais_new' => 'UA'],
            ['id_pais' => 972,  'codigo_pais' => 'UZB', 'nombre_pais' => 'UZBEKISTÁN',                                    'mh_codigo_pais' => '9737', 'mh_codigo_pais_new' => 'UZ'],
            ['id_pais' => 973,  'codigo_pais' => 'VAT', 'nombre_pais' => 'CIUDAD DEL VATICANO',                           'mh_codigo_pais' => '9738', 'mh_codigo_pais_new' => 'VA'],
            ['id_pais' => 974,  'codigo_pais' => 'VAN', 'nombre_pais' => 'VANUATU',                                       'mh_codigo_pais' => '9739', 'mh_codigo_pais_new' => 'VU'],
            ['id_pais' => 976,  'codigo_pais' => 'VMN', 'nombre_pais' => 'VIETNAM NORTE',                                 'mh_codigo_pais' => '9744', 'mh_codigo_pais_new' => null],
            ['id_pais' => 977,  'codigo_pais' => 'VIE', 'nombre_pais' => 'VIETNAM',                                       'mh_codigo_pais' => '9746', 'mh_codigo_pais_new' => 'VN'],
            ['id_pais' => 978,  'codigo_pais' => 'VNS', 'nombre_pais' => 'VIETNAM SUR',                                   'mh_codigo_pais' => '9747', 'mh_codigo_pais_new' => null],
            ['id_pais' => 979,  'codigo_pais' => 'YEM', 'nombre_pais' => 'YEMEN',                                         'mh_codigo_pais' => '9750', 'mh_codigo_pais_new' => 'YE'],
            ['id_pais' => 980,  'codigo_pais' => 'YIB', 'nombre_pais' => 'YIBUTI',                                        'mh_codigo_pais' => '9751', 'mh_codigo_pais_new' => null],
            ['id_pais' => 981,  'codigo_pais' => 'WAL', 'nombre_pais' => 'WALLIS Y FUTUNA, ISLAS',                        'mh_codigo_pais' => '9752', 'mh_codigo_pais_new' => 'WF'],
            ['id_pais' => 982,  'codigo_pais' => 'YUG', 'nombre_pais' => 'YUGOSLAVIA',                                    'mh_codigo_pais' => '9756', 'mh_codigo_pais_new' => null],
            ['id_pais' => 983,  'codigo_pais' => 'ZAI', 'nombre_pais' => 'ZAIRE',                                         'mh_codigo_pais' => '9758', 'mh_codigo_pais_new' => null],
            ['id_pais' => 984,  'codigo_pais' => 'ZAM', 'nombre_pais' => 'ZAMBIA',                                        'mh_codigo_pais' => '9759', 'mh_codigo_pais_new' => 'ZM'],
            ['id_pais' => 985,  'codigo_pais' => 'ZIM', 'nombre_pais' => 'ZIMBABUE',                                      'mh_codigo_pais' => '9760', 'mh_codigo_pais_new' => 'ZW'],
            ['id_pais' => 986,  'codigo_pais' => 'BAH', 'nombre_pais' => 'BAHAMAS',                                       'mh_codigo_pais' => '9862', 'mh_codigo_pais_new' => 'BS'],
            ['id_pais' => 987,  'codigo_pais' => 'BER', 'nombre_pais' => 'BERMUDAS',                                      'mh_codigo_pais' => '9863', 'mh_codigo_pais_new' => 'BM'],
            ['id_pais' => 988,  'codigo_pais' => 'MTN', 'nombre_pais' => 'MARTINICA E.A.',                                'mh_codigo_pais' => '9865', 'mh_codigo_pais_new' => 'MQ'],
            ['id_pais' => 989,  'codigo_pais' => 'PNG', 'nombre_pais' => 'PAPÚA, NUEVA GUINEA',                           'mh_codigo_pais' => '9886', 'mh_codigo_pais_new' => 'PG'],
            ['id_pais' => 990,  'codigo_pais' => 'IGC', 'nombre_pais' => 'CAIMÁN, ISLAS',                                 'mh_codigo_pais' => '9887', 'mh_codigo_pais_new' => 'KY'],
            ['id_pais' => 991,  'codigo_pais' => 'IVB', 'nombre_pais' => 'ISLAS VIRGENES BRITÁNICAS',                     'mh_codigo_pais' => '9897', 'mh_codigo_pais_new' => 'VG'],
            ['id_pais' => 992,  'codigo_pais' => 'ANH', 'nombre_pais' => 'BONAIRE, SINT EUSTATIUS AND SABA',              'mh_codigo_pais' => '9898', 'mh_codigo_pais_new' => 'BQ'],
            ['id_pais' => 993,  'codigo_pais' => 'TW',  'nombre_pais' => 'TAIWAN, PROVINCIA DE CHINA',                    'mh_codigo_pais' => '9899', 'mh_codigo_pais_new' => 'TW'],
            ['id_pais' => 994,  'codigo_pais' => 'VDA', 'nombre_pais' => 'VENDA',                                         'mh_codigo_pais' => '9740', 'mh_codigo_pais_new' => null],
            ['id_pais' => 995,  'codigo_pais' => 'AQ',  'nombre_pais' => 'ANTÁRTICA',                                     'mh_codigo_pais' => null,   'mh_codigo_pais_new' => 'AQ'],
            ['id_pais' => 996,  'codigo_pais' => 'BV',  'nombre_pais' => 'ISLA BOUVET',                                   'mh_codigo_pais' => null,   'mh_codigo_pais_new' => 'BV'],
            ['id_pais' => 997,  'codigo_pais' => 'GS',  'nombre_pais' => 'ISLAS GEORGIAS D. S.-SANDWICH D.S.',            'mh_codigo_pais' => null,   'mh_codigo_pais_new' => 'GS'],
            ['id_pais' => 998,  'codigo_pais' => 'HM',  'nombre_pais' => 'ISLAS HEARD Y MCDONALD',                        'mh_codigo_pais' => null,   'mh_codigo_pais_new' => 'HM'],
            ['id_pais' => 1002, 'codigo_pais' => 'SBL', 'nombre_pais' => 'SAINT BARTHÉLEMY',                              'mh_codigo_pais' => null,   'mh_codigo_pais_new' => 'BL'],
            ['id_pais' => 1003, 'codigo_pais' => 'MF',  'nombre_pais' => 'SAINT MARTIN (FRENCH PART)',                    'mh_codigo_pais' => null,   'mh_codigo_pais_new' => 'MF'],
        ];

        $now = now();

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        foreach ($paises as $pais) {
            DB::table('tbl_pais')->insert([
                'id_pais'            => $pais['id_pais'],
                'codigo_pais'        => trim($pais['codigo_pais']),
                'nombre_pais'        => trim($pais['nombre_pais']),
                'mh_codigo_pais'     => $pais['mh_codigo_pais'],
                'mh_codigo_pais_new' => $pais['mh_codigo_pais_new'],
                'activo'             => true,
                'usuario_crea'       => null,
                'usuario_mod'        => null,
                'usuario_elim'       => null,
                'created_at'         => $now,
                'updated_at'         => $now,
            ]);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}